/* ============================================================
   NDLELA MILLIONAIRES - CENTRAL LEAGUE REGISTRY & CALIBRATION MATRIX
   Scalable configuration-driven league management system.
   Supports: Multiple seasons, competition phases (Apertura/Clausura),
             travel penalties, venue altitudes, dynamic rho, and historical calibration.
   ============================================================ */

export const LEAGUE_REGISTRY = {
  psl: {
    id: 'psl',
    name: 'Betway Premiership',
    country: 'South Africa',
    flag: '🇿🇦',
    competitionType: 'domestic_league',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 98,
    rho: -0.185,
    avgGoals: 2.15,
    homeAdv: 1.28,
    bttsRate: 42.5,
    over15Rate: 68.2,
    over25Rate: 38.4,
    drawRate: 33.1,
    bookmakerMargin: 5.8,
    historicalVolume: 1840,
    accuracyPct: 80.4,
    simulatedRoi: 18.2,
    brierScore: 0.152,
    clvEdge: +4.8,
    bestMarket: 'Under 2.5 / Match Winner (1X)',
    worstMarket: 'Over 3.5 Goals',
    bestModel: 'Dixon-Coles & Venue Fortress Index',
    weakestModel: 'High-Scoring xG Multiplier',
    sources: ['SofaScore PSL Feed', 'Understat Africa', 'Transfermarkt SA', 'Soccer-Wiki Altitude']
  },
  mls: {
    id: 'mls',
    name: 'Major League Soccer (MLS)',
    country: 'United States & Canada',
    flag: '🇺🇸',
    competitionType: 'domestic_conference',
    season: '2026',
    currentPhase: 'Regular Season & Leagues Cup Phase',
    active: true,
    dataQualityScore: 96,
    rho: -0.100,
    avgGoals: 2.94,
    homeAdv: 1.29,
    bttsRate: 58.6,
    over15Rate: 81.4,
    over25Rate: 56.2,
    drawRate: 23.8,
    bookmakerMargin: 5.2,
    historicalVolume: 1250,
    accuracyPct: 78.8,
    simulatedRoi: 15.6,
    brierScore: 0.161,
    clvEdge: +4.2,
    specialRules: {
      crossCountryTravelPenalty: true,
      conferenceRestDelta: true,
      designatedPlayerWeight: 1.35,
      artificialTurfPenalty: 0.08
    },
    bestMarket: 'Over 2.5 / Both Teams To Score',
    worstMarket: 'Under 1.5 Goals',
    bestModel: 'xG Poisson & Travel Fatigue Model',
    weakestModel: 'Low-Scoring Dixon-Coles',
    sources: ['American Soccer Analysis', 'Opta MLS Feed', 'Transfermarkt MLS', 'Soccer-Wiki Travel Mesh']
  },
  scotprem: {
    id: 'scotprem',
    name: 'Scottish Premiership',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    competitionType: 'domestic_league',
    season: '2026/27',
    currentPhase: 'Regular Phase (Split Post-Matchday 33)',
    active: true,
    dataQualityScore: 95,
    rho: -0.130,
    avgGoals: 2.72,
    homeAdv: 1.22,
    bttsRate: 51.4,
    over15Rate: 76.5,
    over25Rate: 52.0,
    drawRate: 24.5,
    bookmakerMargin: 5.4,
    historicalVolume: 960,
    accuracyPct: 79.2,
    simulatedRoi: 14.8,
    brierScore: 0.158,
    clvEdge: +4.1,
    bestMarket: 'Celtic/Rangers Team Over 1.5 & Match Winner',
    worstMarket: 'Draw No Bet Away Underdogs',
    bestModel: 'Elo Dominance Model',
    weakestModel: 'Flat Poisson',
    sources: ['SPFL Official Data', 'WhoScored SPFL', 'Understat UK', 'Transfermarkt Scotland']
  },
  superlig: {
    id: 'superlig',
    name: 'Trendyol Süper Lig',
    country: 'Türkiye',
    flag: '🇹🇷',
    competitionType: 'domestic_league',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 94,
    rho: -0.120,
    avgGoals: 2.76,
    homeAdv: 1.25,
    bttsRate: 54.2,
    over15Rate: 78.1,
    over25Rate: 53.8,
    drawRate: 25.1,
    bookmakerMargin: 5.6,
    historicalVolume: 1100,
    accuracyPct: 77.9,
    simulatedRoi: 13.9,
    brierScore: 0.165,
    clvEdge: +3.9,
    bestMarket: 'Home Team Goals & Over 2.5',
    worstMarket: 'Clean Sheet Away',
    bestModel: 'Home Fortress & Referee Volatility Model',
    weakestModel: 'Neutral Pitch Model',
    sources: ['TFF Ingestion Feed', 'Mackolik Telemetry', 'WhoScored Turkey', 'Transfermarkt Süper Lig']
  },
  ligamx: {
    id: 'ligamx',
    name: 'Liga MX (Apertura / Clausura)',
    country: 'Mexico',
    flag: '🇲🇽',
    competitionType: 'split_tournament',
    season: '2026/27',
    currentPhase: 'Apertura Tournament (Liguilla Race)',
    active: true,
    dataQualityScore: 95,
    rho: -0.130,
    avgGoals: 2.68,
    homeAdv: 1.26,
    bttsRate: 53.5,
    over15Rate: 77.0,
    over25Rate: 51.4,
    drawRate: 26.2,
    bookmakerMargin: 5.5,
    historicalVolume: 1320,
    accuracyPct: 78.6,
    simulatedRoi: 15.1,
    brierScore: 0.160,
    clvEdge: +4.4,
    specialRules: {
      altitudeFortressFactor: true, // Estadio Azteca (2,240m), Nemesio Diez (2,660m)
      phaseAwareness: ['Apertura', 'Clausura', 'Play-In', 'Liguilla']
    },
    bestMarket: 'Home Win & Altitude Decay (Over 1.5)',
    worstMarket: 'Away Clean Sheet at Altitude',
    bestModel: 'Physics Altitude Decay & Dixon-Coles',
    weakestModel: 'Flat Sea-Level Poisson',
    sources: ['Liga BBVA MX Feed', 'MedioTiempo', 'WhoScored Mexico', 'Soccer-Wiki Altitude']
  },
  eliteserien: {
    id: 'eliteserien',
    name: 'Eliteserien',
    country: 'Norway',
    flag: '🇳🇴',
    competitionType: 'summer_calendar_league',
    season: '2026',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 93,
    rho: -0.095,
    avgGoals: 3.08,
    homeAdv: 1.20,
    bttsRate: 60.1,
    over15Rate: 83.2,
    over25Rate: 59.5,
    drawRate: 22.4,
    bookmakerMargin: 5.7,
    historicalVolume: 740,
    accuracyPct: 77.4,
    simulatedRoi: 14.2,
    brierScore: 0.166,
    clvEdge: +3.8,
    bestMarket: 'Over 2.5 Goals / Both Teams To Score',
    worstMarket: 'Under 1.5 Goals',
    bestModel: 'xG Attack Volume Model',
    weakestModel: 'Defensive Shrinkage Model',
    sources: ['NIFS Norway Feed', 'WhoScored Norway', 'Transfermarkt Norway']
  },
  allsvenskan: {
    id: 'allsvenskan',
    name: 'Allsvenskan',
    country: 'Sweden',
    flag: '🇸🇪',
    competitionType: 'summer_calendar_league',
    season: '2026',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 93,
    rho: -0.110,
    avgGoals: 2.82,
    homeAdv: 1.21,
    bttsRate: 55.4,
    over15Rate: 79.2,
    over25Rate: 54.0,
    drawRate: 25.0,
    bookmakerMargin: 5.6,
    historicalVolume: 720,
    accuracyPct: 78.1,
    simulatedRoi: 14.5,
    brierScore: 0.162,
    clvEdge: +4.0,
    bestMarket: 'Over 1.5 / Match Winner Home',
    worstMarket: 'Correct Score 0-0',
    bestModel: 'Momentum & Artificial Turf Specialist Model',
    weakestModel: 'Low-Scoring Dixon-Coles',
    sources: ['Svenskfotboll Official', 'WhoScored Sweden', 'Transfermarkt Sweden']
  },
  superliga: {
    id: 'superliga',
    name: 'Danish Superliga',
    country: 'Denmark',
    flag: '🇩🇰',
    competitionType: 'split_league',
    season: '2026/27',
    currentPhase: 'Regular Season (Pre-Championship Split)',
    active: true,
    dataQualityScore: 94,
    rho: -0.115,
    avgGoals: 2.86,
    homeAdv: 1.19,
    bttsRate: 56.8,
    over15Rate: 80.5,
    over25Rate: 55.2,
    drawRate: 24.8,
    bookmakerMargin: 5.3,
    historicalVolume: 820,
    accuracyPct: 78.5,
    simulatedRoi: 15.0,
    brierScore: 0.159,
    clvEdge: +4.3,
    bestMarket: 'Both Teams To Score / Over 2.5',
    worstMarket: 'Draw Under 1.5',
    bestModel: 'xG & Field Tilt Ensemble',
    weakestModel: 'Flat Poisson',
    sources: ['Superliga.dk Feed', 'WhoScored Denmark', 'Transfermarkt Denmark']
  },
  championship: {
    id: 'championship',
    name: 'English Championship',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    competitionType: 'domestic_tier2',
    season: '2026/27',
    currentPhase: 'Regular Season (46 Matchdays)',
    active: true,
    dataQualityScore: 97,
    rho: -0.135,
    avgGoals: 2.58,
    homeAdv: 1.23,
    bttsRate: 50.8,
    over15Rate: 74.6,
    over25Rate: 48.9,
    drawRate: 27.2,
    bookmakerMargin: 4.8,
    historicalVolume: 2150,
    accuracyPct: 79.4,
    simulatedRoi: 16.2,
    brierScore: 0.155,
    clvEdge: +4.7,
    bestMarket: 'Double Chance (1X) & Under 3.5 Goals',
    worstMarket: 'Away Clean Sheet',
    bestModel: 'Fatigue Congestion & Dixon-Coles',
    weakestModel: 'High xG Bias',
    sources: ['Opta Championship Feed', 'Understat UK', 'WhoScored UK', 'Transfermarkt UK']
  },
  jupiler: {
    id: 'jupiler',
    name: 'Belgium Pro League (Jupiler)',
    country: 'Belgium',
    flag: '🇧🇪',
    competitionType: 'split_playoffs',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 95,
    rho: -0.110,
    avgGoals: 2.88,
    homeAdv: 1.18,
    bttsRate: 57.2,
    over15Rate: 81.0,
    over25Rate: 56.4,
    drawRate: 24.1,
    bookmakerMargin: 5.2,
    historicalVolume: 990,
    accuracyPct: 78.9,
    simulatedRoi: 15.3,
    brierScore: 0.157,
    clvEdge: +4.4,
    bestMarket: 'Over 2.5 & Team Goals Over 1.5',
    worstMarket: 'Under 1.5 Goals',
    bestModel: 'xG / xT Multi-Model Ensemble',
    weakestModel: 'Low Block Defensive Model',
    sources: ['ProLeague.be Feed', 'WhoScored Belgium', 'Transfermarkt Belgium']
  },
  epl: {
    id: 'epl',
    name: 'Premier League',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 99,
    rho: -0.125,
    avgGoals: 2.82,
    homeAdv: 1.18,
    bttsRate: 54.8,
    over15Rate: 79.5,
    over25Rate: 55.0,
    drawRate: 23.5,
    bookmakerMargin: 3.8,
    historicalVolume: 3400,
    accuracyPct: 81.5,
    simulatedRoi: 16.8,
    brierScore: 0.150,
    clvEdge: +5.1,
    bestMarket: 'Match Winner & Team Over 1.5',
    worstMarket: 'Draw No Bet High Odds',
    bestModel: 'Opta/Understat xG + Dixon-Coles Hybrid',
    weakestModel: 'Unadjusted Elo',
    sources: ['Understat Official', 'Opta EPL Feed', 'WhoScored Premier League', 'Transfermarkt UK']
  },
  laliga: {
    id: 'laliga',
    name: 'LaLiga',
    country: 'Spain',
    flag: '🇪🇸',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 98,
    rho: -0.140,
    avgGoals: 2.54,
    homeAdv: 1.22,
    bttsRate: 49.2,
    over15Rate: 73.8,
    over25Rate: 48.0,
    drawRate: 26.8,
    bookmakerMargin: 4.2,
    historicalVolume: 2900,
    accuracyPct: 80.1,
    simulatedRoi: 15.2,
    brierScore: 0.156,
    clvEdge: +4.6,
    bestMarket: 'Under 3.5 & Match Winner Real/Barca',
    worstMarket: 'High Over Lines (Over 4.5)',
    bestModel: 'Tactical Formations & Dixon-Coles',
    weakestModel: 'Unweighted Poisson',
    sources: ['LaLiga Official', 'Understat Spain', 'WhoScored Spain', 'Transfermarkt Spain']
  },
  seriea: {
    id: 'seriea',
    name: 'Serie A',
    country: 'Italy',
    flag: '🇮🇹',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 98,
    rho: -0.155,
    avgGoals: 2.62,
    homeAdv: 1.19,
    bttsRate: 51.5,
    over15Rate: 75.8,
    over25Rate: 50.4,
    drawRate: 25.9,
    bookmakerMargin: 4.4,
    historicalVolume: 2750,
    accuracyPct: 79.7,
    simulatedRoi: 14.9,
    brierScore: 0.158,
    clvEdge: +4.5,
    bestMarket: '1X Double Chance & Corners Under',
    worstMarket: 'Both Teams To Score in Derby Matches',
    bestModel: 'Dixon-Coles Low Rho & Defensive Elo',
    weakestModel: 'High Pace Poisson',
    sources: ['Lega Serie A Feed', 'Understat Italy', 'WhoScored Italy', 'Transfermarkt Italy']
  },
  bundesliga: {
    id: 'bundesliga',
    name: 'Bundesliga',
    country: 'Germany',
    flag: '🇩🇪',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 98,
    rho: -0.090,
    avgGoals: 3.16,
    homeAdv: 1.16,
    bttsRate: 61.2,
    over15Rate: 84.8,
    over25Rate: 62.4,
    drawRate: 22.0,
    bookmakerMargin: 4.1,
    historicalVolume: 2600,
    accuracyPct: 79.1,
    simulatedRoi: 14.6,
    brierScore: 0.162,
    clvEdge: +4.3,
    bestMarket: 'Over 2.5 / Both Teams To Score',
    worstMarket: 'Under 1.5 Goals',
    bestModel: 'High-Pressing xG & Field Tilt Model',
    weakestModel: 'Low-Scoring Poisson',
    sources: ['DFL Bundesliga Feed', 'Understat Germany', 'WhoScored Germany', 'Transfermarkt Germany']
  },
  ligue1: {
    id: 'ligue1',
    name: 'Ligue 1',
    country: 'France',
    flag: '🇫🇷',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 97,
    rho: -0.135,
    avgGoals: 2.66,
    homeAdv: 1.20,
    bttsRate: 52.0,
    over15Rate: 76.2,
    over25Rate: 50.8,
    drawRate: 25.2,
    bookmakerMargin: 4.6,
    historicalVolume: 2400,
    accuracyPct: 78.9,
    simulatedRoi: 14.3,
    brierScore: 0.161,
    clvEdge: +4.2,
    bestMarket: 'PSG Team Over & Under 3.5 in Midtable clashes',
    worstMarket: 'Away Underdogs Win',
    bestModel: 'Squad Valuation & Tactical Elo',
    weakestModel: 'Flat Poisson',
    sources: ['LFP Ligue 1 Feed', 'Understat France', 'WhoScored France', 'Transfermarkt France']
  },
  eredivisie: {
    id: 'eredivisie',
    name: 'Eredivisie',
    country: 'Netherlands',
    flag: '🇳🇱',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 96,
    rho: -0.085,
    avgGoals: 3.12,
    homeAdv: 1.21,
    bttsRate: 59.8,
    over15Rate: 83.5,
    over25Rate: 61.0,
    drawRate: 21.8,
    bookmakerMargin: 4.9,
    historicalVolume: 1800,
    accuracyPct: 78.4,
    simulatedRoi: 14.7,
    brierScore: 0.163,
    clvEdge: +4.2,
    bestMarket: 'Over 2.5 / PSV & Feyenoord Goals',
    worstMarket: 'Under 1.5 Goals',
    bestModel: 'xG Poisson & Attack Velocity',
    weakestModel: 'Dixon-Coles Low Scoring',
    sources: ['Eredivisie.nl Feed', 'WhoScored Netherlands', 'Transfermarkt Netherlands']
  },
  ligaportugal: {
    id: 'ligaportugal',
    name: 'Liga Portugal',
    country: 'Portugal',
    flag: '🇵🇹',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 96,
    rho: -0.145,
    avgGoals: 2.60,
    homeAdv: 1.23,
    bttsRate: 50.5,
    over15Rate: 75.0,
    over25Rate: 49.5,
    drawRate: 25.8,
    bookmakerMargin: 5.0,
    historicalVolume: 1650,
    accuracyPct: 79.8,
    simulatedRoi: 15.4,
    brierScore: 0.157,
    clvEdge: +4.5,
    bestMarket: 'Big 3 (Benfica, Sporting, Porto) Win & Over 1.5',
    worstMarket: 'Away Clean Sheet for Bottom 8',
    bestModel: 'Top-3 Dominance Elo & Dixon-Coles',
    weakestModel: 'Symmetric Poisson',
    sources: ['Liga Portugal Feed', 'WhoScored Portugal', 'Transfermarkt Portugal']
  },
  saudi: {
    id: 'saudi',
    name: 'Saudi Pro League',
    country: 'Saudi Arabia',
    flag: '🇸🇦',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 94,
    rho: -0.105,
    avgGoals: 2.98,
    homeAdv: 1.17,
    bttsRate: 58.0,
    over15Rate: 82.0,
    over25Rate: 58.5,
    drawRate: 22.5,
    bookmakerMargin: 5.5,
    historicalVolume: 850,
    accuracyPct: 78.2,
    simulatedRoi: 14.1,
    brierScore: 0.164,
    clvEdge: +4.0,
    bestMarket: 'Top 4 Team Goals (Al Hilal/Al Nassr) Over 1.5',
    worstMarket: 'Draws in Elite Matches',
    bestModel: 'Squad Value Delta & Attack xG',
    weakestModel: 'Flat Elo',
    sources: ['SPL Official Data', 'Transfermarkt Saudi', 'Soccer-Wiki Middle East']
  },
  brasileirao: {
    id: 'brasileirao',
    name: 'Brasileirão Série A',
    country: 'Brazil',
    flag: '🇧🇷',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'Regular Season (38 Matchdays)',
    active: true,
    dataQualityScore: 95,
    rho: -0.160,
    avgGoals: 2.42,
    homeAdv: 1.30,
    bttsRate: 46.8,
    over15Rate: 71.5,
    over25Rate: 44.2,
    drawRate: 28.5,
    bookmakerMargin: 5.1,
    historicalVolume: 1540,
    accuracyPct: 79.5,
    simulatedRoi: 15.8,
    brierScore: 0.156,
    clvEdge: +4.7,
    bestMarket: 'Home Win (1X) & Under 2.5 Goals',
    worstMarket: 'High Scoring Away Wins',
    bestModel: 'Home Fortress & Physical Congestion Engine',
    weakestModel: 'High Pace Poisson',
    sources: ['CBF Official Data', 'GloboEsporte Feed', 'WhoScored Brazil', 'Transfermarkt Brazil']
  },
  ucl: {
    id: 'ucl',
    name: 'UEFA Champions League',
    country: 'Europe',
    flag: '⭐',
    competitionType: 'continental_champions',
    season: '2026/27',
    currentPhase: 'League Phase & Knockouts',
    active: true,
    dataQualityScore: 99,
    rho: -0.110,
    avgGoals: 2.98,
    homeAdv: 1.15,
    bttsRate: 55.4,
    over15Rate: 83.2,
    over25Rate: 59.8,
    drawRate: 21.2,
    bookmakerMargin: 3.8,
    historicalVolume: 2400,
    accuracyPct: 83.1,
    simulatedRoi: 19.4,
    brierScore: 0.142,
    clvEdge: +5.4,
    bestMarket: 'Team Over 1.5 Goals & Asian Handicap Fav',
    worstMarket: 'Correct Score Speculation',
    bestModel: 'Bivariate Dixon-Coles & UEFA Club Coefficient',
    weakestModel: 'Uniform Elo',
    sources: ['UEFA Official Data Feed', 'Opta Champions League', 'Transfermarkt Europe', 'SofaScore Live']
  },
  uel: {
    id: 'uel',
    name: 'UEFA Europa League',
    country: 'Europe',
    flag: '🏆',
    competitionType: 'continental_tier2',
    season: '2026/27',
    currentPhase: 'League Phase & Knockouts',
    active: true,
    dataQualityScore: 98,
    rho: -0.115,
    avgGoals: 2.85,
    homeAdv: 1.18,
    bttsRate: 56.1,
    over15Rate: 82.0,
    over25Rate: 57.5,
    drawRate: 22.4,
    bookmakerMargin: 4.0,
    historicalVolume: 1800,
    accuracyPct: 81.4,
    simulatedRoi: 17.8,
    brierScore: 0.148,
    clvEdge: +4.9,
    bestMarket: 'Double Chance & Over 1.5 Goals',
    worstMarket: 'Exact Goal Total',
    bestModel: 'Dixon-Coles with Travel Impact',
    weakestModel: 'Uniform Elo',
    sources: ['UEFA Official Data Feed', 'Opta Europa League', 'Transfermarkt Europe', 'SofaScore Live']
  },
  uecl: {
    id: 'uecl',
    name: 'UEFA Conference League',
    country: 'Europe',
    flag: '🌍',
    competitionType: 'continental_tier3',
    season: '2026/27',
    currentPhase: 'League Phase & Knockouts',
    active: true,
    dataQualityScore: 96,
    rho: -0.120,
    avgGoals: 2.78,
    homeAdv: 1.20,
    bttsRate: 54.0,
    over15Rate: 80.5,
    over25Rate: 55.0,
    drawRate: 23.0,
    bookmakerMargin: 4.5,
    historicalVolume: 1200,
    accuracyPct: 79.5,
    simulatedRoi: 16.2,
    brierScore: 0.155,
    clvEdge: +4.5,
    bestMarket: 'Match Winner & Under 3.5 Goals',
    worstMarket: 'Correct Score Speculation',
    bestModel: 'Calibrated Bivariate Poisson',
    weakestModel: 'Static Rating Model',
    sources: ['UEFA Official Data Feed', 'Transfermarkt Europe', 'SofaScore Live']
  },
  austria: {
    id: 'austria',
    name: 'Austrian Bundesliga',
    country: 'Austria',
    flag: '🇦🇹',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season & Championship Round',
    active: true,
    dataQualityScore: 95,
    rho: -0.115,
    avgGoals: 2.84,
    homeAdv: 1.20,
    bttsRate: 54.0,
    over15Rate: 79.2,
    over25Rate: 55.1,
    drawRate: 24.0,
    bookmakerMargin: 5.4,
    historicalVolume: 920,
    accuracyPct: 79.6,
    simulatedRoi: 15.2,
    brierScore: 0.155,
    clvEdge: +4.3,
    bestMarket: 'RB Salzburg / Sturm Graz Over 1.5 Goals & Over 2.5',
    worstMarket: 'Under 1.5 in Relegation Round',
    bestModel: 'High-Press Intensity & Dixon-Coles',
    weakestModel: 'Flat Poisson',
    sources: ['ÖFBL Official Feed', 'WhoScored Austria', 'Transfermarkt Austria']
  },
  ekstraklasa: {
    id: 'ekstraklasa',
    name: 'Ekstraklasa',
    country: 'Poland',
    flag: '🇵🇱',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season (34 Matchdays)',
    active: true,
    dataQualityScore: 94,
    rho: -0.125,
    avgGoals: 2.62,
    homeAdv: 1.24,
    bttsRate: 51.8,
    over15Rate: 75.4,
    over25Rate: 49.2,
    drawRate: 26.5,
    bookmakerMargin: 5.5,
    historicalVolume: 1180,
    accuracyPct: 78.9,
    simulatedRoi: 14.8,
    brierScore: 0.159,
    clvEdge: +4.2,
    bestMarket: 'Double Chance (1X) & BTTS Yes',
    worstMarket: 'Away Clean Sheet for Mid-Table',
    bestModel: 'Physical Duel Index & Dixon-Coles',
    weakestModel: 'Asymmetric Attack Elo',
    sources: ['Ekstraklasa SA Feed', 'Transfermarkt Poland', 'WhoScored Ekstraklasa']
  },
  eng_l1: {
    id: 'eng_l1',
    name: 'English League One',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    competitionType: 'domestic_tier3',
    season: '2026/27',
    currentPhase: 'Regular Season (46 Matchdays)',
    active: true,
    dataQualityScore: 96,
    rho: -0.130,
    avgGoals: 2.64,
    homeAdv: 1.23,
    bttsRate: 52.6,
    over15Rate: 76.8,
    over25Rate: 50.4,
    drawRate: 25.4,
    bookmakerMargin: 5.1,
    historicalVolume: 2200,
    accuracyPct: 79.4,
    simulatedRoi: 16.1,
    brierScore: 0.156,
    clvEdge: +4.6,
    bestMarket: 'Match Winner / Draw No Bet Favorites',
    worstMarket: 'Correct Score & Under 1.5 Goals',
    bestModel: 'Squad Depth Rating & Congestion Model',
    weakestModel: 'Pure Form Momentum',
    sources: ['EFL Official Feed', 'WhoScored EFL', 'Transfermarkt UK']
  },
  eng_l2: {
    id: 'eng_l2',
    name: 'English League Two',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    competitionType: 'domestic_tier4',
    season: '2026/27',
    currentPhase: 'Regular Season (46 Matchdays)',
    active: true,
    dataQualityScore: 95,
    rho: -0.125,
    avgGoals: 2.70,
    homeAdv: 1.25,
    bttsRate: 54.5,
    over15Rate: 78.5,
    over25Rate: 52.8,
    drawRate: 24.8,
    bookmakerMargin: 5.3,
    historicalVolume: 2200,
    accuracyPct: 78.8,
    simulatedRoi: 15.5,
    brierScore: 0.158,
    clvEdge: +4.4,
    bestMarket: 'Both Teams to Score (BTTS) & Over 1.5 Goals',
    worstMarket: 'Away Clean Sheet',
    bestModel: 'Physical Aerobic & Set Piece Engine',
    weakestModel: 'High Precision xG Model',
    sources: ['EFL Official Feed', 'WhoScored League Two', 'Transfermarkt UK']
  },
  ligue2: {
    id: 'ligue2',
    name: 'French Ligue 2',
    country: 'France',
    flag: '🇫🇷',
    competitionType: 'domestic_tier2',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 95,
    rho: -0.165,
    avgGoals: 2.35,
    homeAdv: 1.26,
    bttsRate: 46.2,
    over15Rate: 70.4,
    over25Rate: 41.5,
    drawRate: 31.0,
    bookmakerMargin: 5.4,
    historicalVolume: 1720,
    accuracyPct: 80.2,
    simulatedRoi: 16.9,
    brierScore: 0.153,
    clvEdge: +4.7,
    bestMarket: 'Under 2.5 Goals & Draw (X) / Under 3.5 Goals',
    worstMarket: 'Over 3.5 Goals',
    bestModel: 'Defensive Structure Dixon-Coles & Low-Scoring Tau',
    weakestModel: 'Unbounded Poisson',
    sources: ['LFP Official Data', 'WhoScored France', 'Transfermarkt France']
  },
  bundesliga2: {
    id: 'bundesliga2',
    name: 'German 2. Bundesliga',
    country: 'Germany',
    flag: '🇩🇪',
    competitionType: 'domestic_tier2',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 96,
    rho: -0.095,
    avgGoals: 3.10,
    homeAdv: 1.18,
    bttsRate: 61.2,
    over15Rate: 83.5,
    over25Rate: 60.5,
    drawRate: 22.8,
    bookmakerMargin: 5.0,
    historicalVolume: 1650,
    accuracyPct: 79.5,
    simulatedRoi: 16.4,
    brierScore: 0.157,
    clvEdge: +4.8,
    bestMarket: 'Over 2.5 Goals & Both Teams to Score (BTTS)',
    worstMarket: 'Under 1.5 Goals',
    bestModel: 'End-to-End Transition & Attack Pace Poisson',
    weakestModel: 'Low-Scoring Dixon-Coles',
    sources: ['DFL Official Feed', 'WhoScored 2. Bundesliga', 'Transfermarkt Germany']
  },
  greece: {
    id: 'greece',
    name: 'Greek Super League',
    country: 'Greece',
    flag: '🇬🇷',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season & Play-Offs',
    active: true,
    dataQualityScore: 94,
    rho: -0.150,
    avgGoals: 2.45,
    homeAdv: 1.32,
    bttsRate: 47.0,
    over15Rate: 71.0,
    over25Rate: 43.5,
    drawRate: 28.2,
    bookmakerMargin: 5.6,
    historicalVolume: 1100,
    accuracyPct: 79.7,
    simulatedRoi: 15.6,
    brierScore: 0.155,
    clvEdge: +4.4,
    bestMarket: 'Top 4 (Olympiacos, PAOK, Panathinaikos, AEK) Win & Under 3.5',
    worstMarket: 'Away Win for Bottom 6',
    bestModel: 'Fortress Venue & Big-4 Hierarchy Model',
    weakestModel: 'Uniform Elo Spread',
    sources: ['Super League Greece Feed', 'Transfermarkt Greece', 'Soccer-Wiki Greece']
  },
  serieb: {
    id: 'serieb',
    name: 'Italian Serie B',
    country: 'Italy',
    flag: '🇮🇹',
    competitionType: 'domestic_tier2',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 95,
    rho: -0.160,
    avgGoals: 2.40,
    homeAdv: 1.25,
    bttsRate: 48.1,
    over15Rate: 72.0,
    over25Rate: 42.8,
    drawRate: 30.5,
    bookmakerMargin: 5.2,
    historicalVolume: 1850,
    accuracyPct: 80.1,
    simulatedRoi: 16.8,
    brierScore: 0.154,
    clvEdge: +4.6,
    bestMarket: 'Under 2.5 Goals / Double Chance (1X)',
    worstMarket: 'Over 3.5 Goals',
    bestModel: 'Tactical Defensive Rigidity & Dixon-Coles Tau',
    weakestModel: 'Open Pitch Poisson',
    sources: ['Lega B Official Data', 'WhoScored Italy', 'Transfermarkt Italy']
  },
  russia: {
    id: 'russia',
    name: 'Russian Premier League',
    country: 'Russia',
    flag: '🇷🇺',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 94,
    rho: -0.135,
    avgGoals: 2.65,
    homeAdv: 1.27,
    bttsRate: 50.8,
    over15Rate: 75.2,
    over25Rate: 49.5,
    drawRate: 26.0,
    bookmakerMargin: 5.5,
    historicalVolume: 1200,
    accuracyPct: 79.1,
    simulatedRoi: 15.0,
    brierScore: 0.157,
    clvEdge: +4.3,
    bestMarket: 'Zenit / Krasnodar Win & Over 1.5',
    worstMarket: 'Away Dogs in Winter Rounds',
    bestModel: 'Climate & Travel Strain Index',
    weakestModel: 'Generic Temperature Model',
    sources: ['RPL Official Feed', 'WhoScored Russia', 'Transfermarkt Russia']
  },
  laliga2: {
    id: 'laliga2',
    name: 'Spanish LALIGA 2',
    country: 'Spain',
    flag: '🇪🇸',
    competitionType: 'domestic_tier2',
    season: '2026/27',
    currentPhase: 'Regular Season (42 Matchdays)',
    active: true,
    dataQualityScore: 96,
    rho: -0.170,
    avgGoals: 2.25,
    homeAdv: 1.28,
    bttsRate: 44.5,
    over15Rate: 68.5,
    over25Rate: 38.0,
    drawRate: 32.2,
    bookmakerMargin: 5.1,
    historicalVolume: 2100,
    accuracyPct: 80.8,
    simulatedRoi: 17.5,
    brierScore: 0.151,
    clvEdge: +4.9,
    bestMarket: 'Under 2.5 Goals / Draw at Half Time',
    worstMarket: 'Over 3.5 Goals',
    bestModel: 'Low-Scoring Dixon-Coles & Tactical Press',
    weakestModel: 'Attack-Heavy Poisson',
    sources: ['LaLiga Official Data', 'WhoScored Spain', 'Transfermarkt Spain']
  },
  swiss: {
    id: 'swiss',
    name: 'Swiss Super League',
    country: 'Switzerland',
    flag: '🇨🇭',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season & Championship Round',
    active: true,
    dataQualityScore: 95,
    rho: -0.105,
    avgGoals: 2.95,
    homeAdv: 1.21,
    bttsRate: 59.0,
    over15Rate: 81.5,
    over25Rate: 58.0,
    drawRate: 23.5,
    bookmakerMargin: 5.3,
    historicalVolume: 980,
    accuracyPct: 79.3,
    simulatedRoi: 15.4,
    brierScore: 0.158,
    clvEdge: +4.4,
    bestMarket: 'Over 2.5 Goals & Both Teams to Score',
    worstMarket: 'Under 1.5 Goals',
    bestModel: 'Attacking Space & Transition Poisson',
    weakestModel: 'Low Variance Dixon-Coles',
    sources: ['SFL Official Data', 'WhoScored Switzerland', 'Transfermarkt Switzerland']
  },
  ukraine: {
    id: 'ukraine',
    name: 'Ukrainian Premier League',
    country: 'Ukraine',
    flag: '🇺🇦',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 93,
    rho: -0.145,
    avgGoals: 2.50,
    homeAdv: 1.22,
    bttsRate: 48.5,
    over15Rate: 72.8,
    over25Rate: 45.0,
    drawRate: 27.5,
    bookmakerMargin: 5.7,
    historicalVolume: 890,
    accuracyPct: 78.6,
    simulatedRoi: 14.5,
    brierScore: 0.160,
    clvEdge: +4.1,
    bestMarket: 'Shakhtar / Dynamo Kyiv Win & Under 3.5 Goals',
    worstMarket: 'Both Teams to Score Yes in Relegation Duels',
    bestModel: 'Top-2 Hegemony & Venue Neutralizer Model',
    weakestModel: 'Standard Home Advantage',
    sources: ['UPL Official Data', 'Transfermarkt Ukraine', 'Soccer-Wiki Eastern Europe']
  },
  caf_cl: {
    id: 'caf_cl',
    name: 'CAF Champions League',
    country: 'Africa',
    flag: '🌍',
    competitionType: 'continental_champions',
    season: '2026/27',
    currentPhase: 'Group Stage & Knockout Rounds',
    active: true,
    dataQualityScore: 97,
    rho: -0.165,
    avgGoals: 2.28,
    homeAdv: 1.38,
    bttsRate: 43.5,
    over15Rate: 69.2,
    over25Rate: 40.8,
    drawRate: 29.5,
    bookmakerMargin: 5.6,
    historicalVolume: 1450,
    accuracyPct: 81.2,
    simulatedRoi: 17.8,
    brierScore: 0.150,
    clvEdge: +5.1,
    bestMarket: 'Home Win (1) / 1X & Under 2.5 Goals',
    worstMarket: 'Away Clean Sheet in Sub-Saharan / North Africa Ties',
    bestModel: 'Extreme Home Fortress & Continental Travel Fatigue',
    weakestModel: 'Neutral Pitch Poisson',
    sources: ['CAF Official Data', 'Transfermarkt Africa', 'SofaScore CAF']
  },
  caf_cc: {
    id: 'caf_cc',
    name: 'CAF Confederation Cup',
    country: 'Africa',
    flag: '🏆',
    competitionType: 'continental_secondary',
    season: '2026/27',
    currentPhase: 'Group Stage & Knockouts',
    active: true,
    dataQualityScore: 95,
    rho: -0.160,
    avgGoals: 2.32,
    homeAdv: 1.36,
    bttsRate: 44.8,
    over15Rate: 70.5,
    over25Rate: 42.0,
    drawRate: 28.8,
    bookmakerMargin: 5.8,
    historicalVolume: 1200,
    accuracyPct: 80.4,
    simulatedRoi: 17.0,
    brierScore: 0.153,
    clvEdge: +4.9,
    bestMarket: 'Home Win (1X) & Under 2.5 Goals',
    worstMarket: 'High Scoring Away Contests',
    bestModel: 'Host Altitude & Hostility Factor Model',
    weakestModel: 'Flat Elo Spread',
    sources: ['CAF Official Data', 'Transfermarkt Africa', 'SofaScore CAF']
  },
  botola: {
    id: 'botola',
    name: 'Botola Pro',
    country: 'Morocco',
    flag: '🇲🇦',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season (30 Matchdays)',
    active: true,
    dataQualityScore: 95,
    rho: -0.180,
    avgGoals: 2.18,
    homeAdv: 1.29,
    bttsRate: 41.5,
    over15Rate: 67.5,
    over25Rate: 37.2,
    drawRate: 33.5,
    bookmakerMargin: 5.5,
    historicalVolume: 1100,
    accuracyPct: 80.6,
    simulatedRoi: 17.4,
    brierScore: 0.151,
    clvEdge: +4.8,
    bestMarket: 'Under 2.5 Goals / Draw (X) / Casablanca Win (1X)',
    worstMarket: 'Over 3.5 Goals',
    bestModel: 'Low-Scoring Dixon-Coles & North African Tactical Engine',
    weakestModel: 'High Pace Poisson',
    sources: ['FRMF Official Feed', 'Transfermarkt Morocco', 'Soccer-Wiki Maghreb']
  },
  egypt: {
    id: 'egypt',
    name: 'Egyptian Premier League',
    country: 'Egypt',
    flag: '🇪🇬',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 96,
    rho: -0.175,
    avgGoals: 2.22,
    homeAdv: 1.26,
    bttsRate: 43.0,
    over15Rate: 68.8,
    over25Rate: 38.5,
    drawRate: 32.0,
    bookmakerMargin: 5.4,
    historicalVolume: 1250,
    accuracyPct: 81.0,
    simulatedRoi: 17.6,
    brierScore: 0.149,
    clvEdge: +5.0,
    bestMarket: 'Al Ahly / Zamalek / Pyramids Win & Under 3.5 Goals',
    worstMarket: 'Both Teams to Score Yes for Lower Half',
    bestModel: 'Elite Big-3 Dominance & Dixon-Coles Low Tau',
    weakestModel: 'Symmetric Elo Model',
    sources: ['EFA Official Feed', 'Transfermarkt Egypt', 'SofaScore Egypt']
  },
  afc_cl: {
    id: 'afc_cl',
    name: 'AFC Champions League Elite',
    country: 'Asia',
    flag: '🌏',
    competitionType: 'continental_champions',
    season: '2026/27',
    currentPhase: 'League Stage (West & East Zones)',
    active: true,
    dataQualityScore: 97,
    rho: -0.115,
    avgGoals: 2.92,
    homeAdv: 1.25,
    bttsRate: 57.2,
    over15Rate: 80.8,
    over25Rate: 56.4,
    drawRate: 22.4,
    bookmakerMargin: 5.2,
    historicalVolume: 1400,
    accuracyPct: 80.8,
    simulatedRoi: 17.2,
    brierScore: 0.152,
    clvEdge: +4.8,
    bestMarket: 'Saudi / Japanese / Korean Giants Win & Over 1.5 Goals',
    worstMarket: 'Under 1.5 in East Zone Clashes',
    bestModel: 'Squad Market Cap Asymmetry & Continental Travel Model',
    weakestModel: 'Zone-Agnostic Poisson',
    sources: ['AFC Official Data', 'Transfermarkt Asia', 'SofaScore Asia']
  },
  aleague: {
    id: 'aleague',
    name: 'Australian A-League Men',
    country: 'Australia',
    flag: '🇦🇺',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season & Finals Series',
    active: true,
    dataQualityScore: 95,
    rho: -0.090,
    avgGoals: 3.14,
    homeAdv: 1.20,
    bttsRate: 63.5,
    over15Rate: 84.8,
    over25Rate: 62.0,
    drawRate: 21.8,
    bookmakerMargin: 5.1,
    historicalVolume: 980,
    accuracyPct: 79.5,
    simulatedRoi: 16.2,
    brierScore: 0.156,
    clvEdge: +4.7,
    bestMarket: 'Both Teams to Score (BTTS) & Over 2.5 Goals',
    worstMarket: 'Under 2.5 Goals / Clean Sheet',
    bestModel: 'High-Scoring xG Poisson & Travel Fatigue Engine',
    weakestModel: 'Low-Scoring Dixon-Coles',
    sources: ['A-Leagues Official Feed', 'WhoScored Australia', 'Transfermarkt Australia']
  },
  csl: {
    id: 'csl',
    name: 'Chinese Super League',
    country: 'China',
    flag: '🇨🇳',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'Regular Season (30 Matchdays)',
    active: true,
    dataQualityScore: 94,
    rho: -0.105,
    avgGoals: 2.96,
    homeAdv: 1.22,
    bttsRate: 58.2,
    over15Rate: 81.2,
    over25Rate: 57.5,
    drawRate: 23.2,
    bookmakerMargin: 5.3,
    historicalVolume: 1150,
    accuracyPct: 78.9,
    simulatedRoi: 15.1,
    brierScore: 0.158,
    clvEdge: +4.3,
    bestMarket: 'Shanghai Port / Shenhua Win & Over 2.5 Goals',
    worstMarket: 'Under 1.5 Goals',
    bestModel: 'Foreign Striker Dependency & xG Model',
    weakestModel: 'Defensive Rating Multiplier',
    sources: ['CSL Official Feed', 'WhoScored China', 'Transfermarkt China']
  },
  j1: {
    id: 'j1',
    name: 'Japan J1 League',
    country: 'Japan',
    flag: '🇯🇵',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'Regular Season (38 Matchdays)',
    active: true,
    dataQualityScore: 96,
    rho: -0.130,
    avgGoals: 2.62,
    homeAdv: 1.18,
    bttsRate: 51.5,
    over15Rate: 75.8,
    over25Rate: 49.0,
    drawRate: 26.8,
    bookmakerMargin: 5.0,
    historicalVolume: 1520,
    accuracyPct: 80.0,
    simulatedRoi: 16.0,
    brierScore: 0.154,
    clvEdge: +4.6,
    bestMarket: 'Under 3.5 Goals & Double Chance (1X/X2)',
    worstMarket: 'Extreme Blowout Bets',
    bestModel: 'High Discipline Tactical Poisson & Dixon-Coles',
    weakestModel: 'High Skew Poisson',
    sources: ['J.League Official Feed', 'WhoScored Japan', 'Transfermarkt Japan']
  },
  argliga: {
    id: 'argliga',
    name: 'Argentine Liga Profesional',
    country: 'Argentina',
    flag: '🇦🇷',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'Torneo Apertura & Clausura',
    active: true,
    dataQualityScore: 96,
    rho: -0.175,
    avgGoals: 2.15,
    homeAdv: 1.30,
    bttsRate: 41.8,
    over15Rate: 67.2,
    over25Rate: 36.8,
    drawRate: 33.8,
    bookmakerMargin: 5.1,
    historicalVolume: 1980,
    accuracyPct: 81.4,
    simulatedRoi: 18.2,
    brierScore: 0.148,
    clvEdge: +5.2,
    bestMarket: 'Under 2.5 Goals / Draw (X) / River & Boca 1X',
    worstMarket: 'Over 3.5 Goals',
    bestModel: 'Bivariate Dixon-Coles Low Tau & Physical Duel Engine',
    weakestModel: 'High-Scoring Poisson',
    sources: ['AFA Official Feed', 'WhoScored Argentina', 'Transfermarkt Argentina']
  },
  bolivia: {
    id: 'bolivia',
    name: 'Bolivian Liga Profesional',
    country: 'Bolivia',
    flag: '🇧🇴',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'Torneo Todos Contra Todos & Copa',
    active: true,
    dataQualityScore: 94,
    rho: -0.110,
    avgGoals: 3.02,
    homeAdv: 1.48,
    bttsRate: 58.5,
    over15Rate: 82.0,
    over25Rate: 58.5,
    drawRate: 20.8,
    bookmakerMargin: 5.8,
    historicalVolume: 920,
    accuracyPct: 81.8,
    simulatedRoi: 19.0,
    brierScore: 0.147,
    clvEdge: +5.6,
    bestMarket: 'La Paz / El Alto High Altitude Home Win (1)',
    worstMarket: 'Lowland Teams Winning in Altitude',
    bestModel: 'Altitude Hypoxia Fortress Model (SoccerWiki 3600m+ Index)',
    weakestModel: 'Altitude-Blind Elo Spread',
    sources: ['FBF Official Feed', 'Soccer-Wiki Altitude Matrix', 'Transfermarkt Bolivia']
  },
  chile: {
    id: 'chile',
    name: 'Chilean Primera División',
    country: 'Chile',
    flag: '🇨🇱',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'Campeonato Nacional (30 Matchdays)',
    active: true,
    dataQualityScore: 94,
    rho: -0.135,
    avgGoals: 2.68,
    homeAdv: 1.25,
    bttsRate: 53.0,
    over15Rate: 77.0,
    over25Rate: 51.5,
    drawRate: 25.5,
    bookmakerMargin: 5.4,
    historicalVolume: 1100,
    accuracyPct: 79.2,
    simulatedRoi: 15.3,
    brierScore: 0.157,
    clvEdge: +4.4,
    bestMarket: 'Colo-Colo / U. de Chile Win & Over 1.5',
    worstMarket: 'Away Clean Sheet in Northern Desert Ties',
    bestModel: 'Classic Chilean Transition & Dixon-Coles',
    weakestModel: 'Flat Poisson',
    sources: ['ANFP Official Feed', 'WhoScored Chile', 'Transfermarkt Chile']
  },
  colombia: {
    id: 'colombia',
    name: 'Colombia Primera A, Apertura',
    country: 'Colombia',
    flag: '🇨🇴',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'Liga BetPlay Dimayor Apertura',
    active: true,
    dataQualityScore: 95,
    rho: -0.165,
    avgGoals: 2.26,
    homeAdv: 1.34,
    bttsRate: 43.8,
    over15Rate: 69.5,
    over25Rate: 39.2,
    drawRate: 31.8,
    bookmakerMargin: 5.3,
    historicalVolume: 1600,
    accuracyPct: 80.7,
    simulatedRoi: 17.5,
    brierScore: 0.151,
    clvEdge: +5.0,
    bestMarket: 'Under 2.5 Goals / Home Win in Bogotá Altitude (2600m)',
    worstMarket: 'Over 3.5 Goals',
    bestModel: 'Bogotá / Medellín Altitude & Dixon-Coles Low Tau',
    weakestModel: 'High Pace Poisson',
    sources: ['DIMAYOR Official Feed', 'Transfermarkt Colombia', 'Soccer-Wiki Colombia']
  },
  libertadores: {
    id: 'libertadores',
    name: 'CONMEBOL Libertadores',
    country: 'South America',
    flag: '🏆',
    competitionType: 'continental_champions',
    season: '2026',
    currentPhase: 'Fase de Grupos & Mata-Mata',
    active: true,
    dataQualityScore: 98,
    rho: -0.140,
    avgGoals: 2.65,
    homeAdv: 1.35,
    bttsRate: 50.5,
    over15Rate: 76.5,
    over25Rate: 50.0,
    drawRate: 25.8,
    bookmakerMargin: 4.8,
    historicalVolume: 1800,
    accuracyPct: 81.6,
    simulatedRoi: 18.5,
    brierScore: 0.149,
    clvEdge: +5.2,
    bestMarket: 'Home Advantage / Brazilian & Argentine Powerhouses Win',
    worstMarket: 'Away Clean Sheet at Altitude or Hostile Venues',
    bestModel: 'CONMEBOL Fortress & Club Valuation Matrix',
    weakestModel: 'Neutral Field Elo',
    sources: ['CONMEBOL Official Data', 'GloboEsporte', 'Transfermarkt South America']
  },
  sudamericana: {
    id: 'sudamericana',
    name: 'CONMEBOL Sudamericana',
    country: 'South America',
    flag: '🥈',
    competitionType: 'continental_secondary',
    season: '2026',
    currentPhase: 'Fase de Grupos & Play-Offs',
    active: true,
    dataQualityScore: 96,
    rho: -0.145,
    avgGoals: 2.58,
    homeAdv: 1.33,
    bttsRate: 49.0,
    over15Rate: 74.8,
    over25Rate: 48.0,
    drawRate: 26.5,
    bookmakerMargin: 5.2,
    historicalVolume: 1450,
    accuracyPct: 80.5,
    simulatedRoi: 17.1,
    brierScore: 0.153,
    clvEdge: +4.9,
    bestMarket: 'Home Win (1X) & Under 3.5 Goals',
    worstMarket: 'Underdog Away Wins',
    bestModel: 'Travel Stress & Home Crowd Intensity Engine',
    weakestModel: 'Flat Poisson',
    sources: ['CONMEBOL Official Data', 'Transfermarkt South America', 'SofaScore CONMEBOL']
  },
  uruguay: {
    id: 'uruguay',
    name: 'Liga AUF Uruguaya',
    country: 'Uruguay',
    flag: '🇺🇾',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'Torneo Clausura & Tabla Anual',
    active: true,
    dataQualityScore: 94,
    rho: -0.155,
    avgGoals: 2.38,
    homeAdv: 1.25,
    bttsRate: 46.5,
    over15Rate: 71.8,
    over25Rate: 42.0,
    drawRate: 30.0,
    bookmakerMargin: 5.6,
    historicalVolume: 950,
    accuracyPct: 80.2,
    simulatedRoi: 16.7,
    brierScore: 0.153,
    clvEdge: +4.7,
    bestMarket: 'Peñarol / Nacional Win & Under 3.5 Goals',
    worstMarket: 'Over 3.5 Goals in Intermedio',
    bestModel: 'Montevideo Big-2 Dominance & Dixon-Coles',
    weakestModel: 'Symmetric Multiplier',
    sources: ['AUF Official Feed', 'Tenfield / AUFTV Data', 'Transfermarkt Uruguay']
  },
  ecuador: {
    id: 'ecuador',
    name: 'LigaPro Ecuador',
    country: 'Ecuador',
    flag: '🇪🇨',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'Fase 2 (16 Equipos)',
    active: true,
    dataQualityScore: 94,
    rho: -0.130,
    avgGoals: 2.72,
    homeAdv: 1.36,
    bttsRate: 53.5,
    over15Rate: 77.8,
    over25Rate: 52.4,
    drawRate: 24.5,
    bookmakerMargin: 5.5,
    historicalVolume: 1050,
    accuracyPct: 80.8,
    simulatedRoi: 17.6,
    brierScore: 0.151,
    clvEdge: +5.1,
    bestMarket: 'Quito Altitude Clash (LDU / IDV) Home Win & Over 1.5',
    worstMarket: 'Guayaquil Coastal Teams in Quito (2850m) Altitude',
    bestModel: 'Sierra vs Costa Altitude & Climate Friction Index',
    weakestModel: 'Altitude-Insensitive Poisson',
    sources: ['LigaPro Official Feed', 'Transfermarkt Ecuador', 'Soccer-Wiki Ecuador']
  },
  paraguay: {
    id: 'paraguay',
    name: 'Paraguayan Primera División',
    country: 'Paraguay',
    flag: '🇵🇾',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'Torneo Clausura Copa de Primera',
    active: true,
    dataQualityScore: 94,
    rho: -0.145,
    avgGoals: 2.54,
    homeAdv: 1.27,
    bttsRate: 49.5,
    over15Rate: 74.0,
    over25Rate: 46.5,
    drawRate: 27.8,
    bookmakerMargin: 5.5,
    historicalVolume: 1020,
    accuracyPct: 79.8,
    simulatedRoi: 16.2,
    brierScore: 0.155,
    clvEdge: +4.6,
    bestMarket: 'Libertad / Olimpia / Cerro Porteño Win & Under 3.5',
    worstMarket: 'Away Wins for Bottom 4',
    bestModel: 'Asunción Big-3 Monopoly & Dixon-Coles',
    weakestModel: 'Open Space Poisson',
    sources: ['APF Official Feed', 'Tigo Sports Data', 'Transfermarkt Paraguay']
  },
  peru: {
    id: 'peru',
    name: 'Peruvian Liga 1',
    country: 'Peru',
    flag: '🇵🇪',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'Torneo Clausura Liga 1 Te Apuesto',
    active: true,
    dataQualityScore: 94,
    rho: -0.125,
    avgGoals: 2.76,
    homeAdv: 1.42,
    bttsRate: 54.0,
    over15Rate: 78.5,
    over25Rate: 53.0,
    drawRate: 23.5,
    bookmakerMargin: 5.6,
    historicalVolume: 1120,
    accuracyPct: 81.2,
    simulatedRoi: 18.4,
    brierScore: 0.149,
    clvEdge: +5.3,
    bestMarket: 'Andean Altitude Venue Win (Cusco / Tarma / Huancayo)',
    worstMarket: 'Coastal Lima Teams Winning at 3300m+ Altitude',
    bestModel: 'High Altitude Hypoxia & Thermal Friction Model',
    weakestModel: 'Flat Elo Model',
    sources: ['FPF Liga 1 Official Feed', 'Transfermarkt Peru', 'Soccer-Wiki Peru']
  },
  venezuela: {
    id: 'venezuela',
    name: 'Venezuelan Primera División',
    country: 'Venezuela',
    flag: '🇻🇪',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'Liga FUTVE Clausura',
    active: true,
    dataQualityScore: 93,
    rho: -0.160,
    avgGoals: 2.30,
    homeAdv: 1.30,
    bttsRate: 45.0,
    over15Rate: 70.0,
    over25Rate: 40.5,
    drawRate: 31.0,
    bookmakerMargin: 5.8,
    historicalVolume: 880,
    accuracyPct: 79.5,
    simulatedRoi: 15.9,
    brierScore: 0.156,
    clvEdge: +4.6,
    bestMarket: 'Deportivo Táchira / Caracas FC 1X & Under 2.5 Goals',
    worstMarket: 'Over 3.5 Goals',
    bestModel: 'Low Variance Dixon-Coles & Home Fortress Factor',
    weakestModel: 'High Pace Poisson',
    sources: ['Liga FUTVE Official Feed', 'Transfermarkt Venezuela', 'Soccer-Wiki Caribbean']
  },
  guatemala: {
    id: 'guatemala',
    name: 'Guatemalan Liga Nacional',
    country: 'Guatemala',
    flag: '🇬🇹',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Torneo Apertura Liga Guate Banrural',
    active: true,
    dataQualityScore: 93,
    rho: -0.160,
    avgGoals: 2.34,
    homeAdv: 1.35,
    bttsRate: 45.5,
    over15Rate: 70.5,
    over25Rate: 41.2,
    drawRate: 30.5,
    bookmakerMargin: 5.7,
    historicalVolume: 860,
    accuracyPct: 80.0,
    simulatedRoi: 16.5,
    brierScore: 0.154,
    clvEdge: +4.8,
    bestMarket: 'Municipal / Comunicaciones Home Win (1) & Under 3.5',
    worstMarket: 'Away Clean Sheet',
    bestModel: 'Clásico Chapín Monopoly & Extreme Home Advantage',
    weakestModel: 'Uniform Neutral Poisson',
    sources: ['Liga Nacional GT Official Feed', 'Transfermarkt Guatemala', 'Soccer-Wiki Central America']
  },
  uefa_nations: {
    id: 'uefa_nations',
    name: 'UEFA Nations League',
    country: 'Europe',
    flag: '🇪🇺',
    competitionType: 'international_nations',
    season: '2026/27',
    currentPhase: 'League Phase & Finals',
    active: true,
    dataQualityScore: 98,
    rho: -0.125,
    avgGoals: 2.65,
    homeAdv: 1.16,
    bttsRate: 51.5,
    over15Rate: 77.2,
    over25Rate: 51.0,
    drawRate: 26.5,
    bookmakerMargin: 4.8,
    historicalVolume: 1120,
    accuracyPct: 81.2,
    simulatedRoi: 16.8,
    brierScore: 0.150,
    clvEdge: +4.9,
    bestMarket: '1X2 Home Win & Over 1.5 Goals',
    worstMarket: 'Extreme Under 0.5',
    bestModel: 'Bivariate Dixon-Coles International Elo',
    weakestModel: 'Domestic Fixture Bias',
    sources: ['UEFA Official Feed', 'SofaScore Europe', 'Transfermarkt International']
  },
  afcon: {
    id: 'afcon',
    name: 'African Cup of Nations',
    country: 'Africa',
    flag: '🌍',
    competitionType: 'international_championship',
    season: '2026',
    currentPhase: 'Qualifiers & Tournament Finals',
    active: true,
    dataQualityScore: 96,
    rho: -0.170,
    avgGoals: 2.18,
    homeAdv: 1.10,
    bttsRate: 40.5,
    over15Rate: 66.8,
    over25Rate: 37.5,
    drawRate: 32.5,
    bookmakerMargin: 5.6,
    historicalVolume: 940,
    accuracyPct: 80.8,
    simulatedRoi: 17.6,
    brierScore: 0.152,
    clvEdge: +5.1,
    bestMarket: 'Under 2.5 Goals / Double Chance (1X)',
    worstMarket: 'Over 3.5 Goals',
    bestModel: 'Low-Variance Dixon-Coles & Defensive Rating Shield',
    weakestModel: 'High-Scoring xG Multiplier',
    sources: ['CAF Official Data', 'Understat Africa', 'SofaScore AFCON']
  },
  kategoria_superiore: {
    id: 'kategoria_superiore',
    name: 'Kategoria Superiore',
    country: 'Albania',
    flag: '🇦🇱',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 92,
    rho: -0.160,
    avgGoals: 2.30,
    homeAdv: 1.30,
    bttsRate: 43.5,
    over15Rate: 68.5,
    over25Rate: 39.5,
    drawRate: 31.0,
    bookmakerMargin: 6.0,
    historicalVolume: 620,
    accuracyPct: 79.5,
    simulatedRoi: 15.2,
    brierScore: 0.156,
    clvEdge: +4.2,
    bestMarket: 'Under 2.5 Goals / Home Advantage',
    worstMarket: 'Away Over 2.5',
    bestModel: 'Balkan Defensive Grid & Dixon-Coles',
    weakestModel: 'High-Pace Attacking Poisson',
    sources: ['FSHF Official Feed', 'Transfermarkt Albania']
  },
  armenia: {
    id: 'armenia',
    name: 'Armenian Premier League',
    country: 'Armenia',
    flag: '🇦🇲',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 91,
    rho: -0.135,
    avgGoals: 2.65,
    homeAdv: 1.25,
    bttsRate: 48.0,
    over15Rate: 74.0,
    over25Rate: 47.5,
    drawRate: 27.5,
    bookmakerMargin: 6.2,
    historicalVolume: 580,
    accuracyPct: 79.0,
    simulatedRoi: 14.8,
    brierScore: 0.158,
    clvEdge: +4.0,
    bestMarket: 'Match Winner / Over 1.5 Goals',
    worstMarket: 'Under 1.5 Goals in Top 4 Clashes',
    bestModel: 'Pyunik-Noah Dominance Rating Model',
    weakestModel: 'Flat Poisson',
    sources: ['FFA Armenian League', 'Transfermarkt Armenia']
  },
  austria_erste: {
    id: 'austria_erste',
    name: 'Austrian Erste Liga',
    country: 'Austria',
    flag: '🇦🇹',
    competitionType: 'domestic_tier2',
    season: '2026/27',
    currentPhase: '2. Liga Regular Season',
    active: true,
    dataQualityScore: 95,
    rho: -0.100,
    avgGoals: 2.95,
    homeAdv: 1.22,
    bttsRate: 56.5,
    over15Rate: 81.0,
    over25Rate: 55.0,
    drawRate: 25.0,
    bookmakerMargin: 5.4,
    historicalVolume: 920,
    accuracyPct: 80.2,
    simulatedRoi: 16.0,
    brierScore: 0.154,
    clvEdge: +4.6,
    bestMarket: 'Over 2.5 Goals / Both Teams To Score',
    worstMarket: 'Under 1.5 Goals',
    bestModel: 'Austrian High-Tempo Pressing & Dixon-Coles',
    weakestModel: 'Low-Scoring Neutral Model',
    sources: ['Bundesliga.at 2. Liga', 'SofaScore Austria']
  },
  azerbaijan: {
    id: 'azerbaijan',
    name: 'Misli Premier League',
    country: 'Azerbaijan',
    flag: '🇦🇿',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Misli Premyer Liqası',
    active: true,
    dataQualityScore: 93,
    rho: -0.155,
    avgGoals: 2.38,
    homeAdv: 1.28,
    bttsRate: 44.0,
    over15Rate: 70.0,
    over25Rate: 41.5,
    drawRate: 29.5,
    bookmakerMargin: 5.8,
    historicalVolume: 640,
    accuracyPct: 80.5,
    simulatedRoi: 15.8,
    brierScore: 0.153,
    clvEdge: +4.5,
    bestMarket: 'Qarabağ Win & Over 1.5 / Under 2.5 Others',
    worstMarket: 'Away Clean Sheet vs Top 2',
    bestModel: 'Qarabağ Monopoly & Defensive Index',
    weakestModel: 'Neutral Dispersion Model',
    sources: ['PFL Azerbaijan', 'Transfermarkt Azerbaijan']
  },
  bosnia: {
    id: 'bosnia',
    name: 'Bosnia and Herzegovina Premijer Liga',
    country: 'Bosnia & Herzegovina',
    flag: '🇧🇦',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'WWin Premijer Liga',
    active: true,
    dataQualityScore: 92,
    rho: -0.150,
    avgGoals: 2.45,
    homeAdv: 1.32,
    bttsRate: 46.0,
    over15Rate: 71.5,
    over25Rate: 44.0,
    drawRate: 28.5,
    bookmakerMargin: 5.9,
    historicalVolume: 710,
    accuracyPct: 79.8,
    simulatedRoi: 15.4,
    brierScore: 0.155,
    clvEdge: +4.4,
    bestMarket: 'Home Advantage (1X) & Under 3.5',
    worstMarket: 'High-Scoring Shootouts',
    bestModel: 'Balkan Hostile Venue & Dixon-Coles',
    weakestModel: 'Open Space xG Model',
    sources: ['NFSBiH Official Feed', 'Transfermarkt Bosnia']
  },
  bulgaria: {
    id: 'bulgaria',
    name: 'Bulgarian First Professional League',
    country: 'Bulgaria',
    flag: '🇧🇬',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'efbet Liga Championship Round',
    active: true,
    dataQualityScore: 94,
    rho: -0.145,
    avgGoals: 2.48,
    homeAdv: 1.28,
    bttsRate: 47.0,
    over15Rate: 72.0,
    over25Rate: 45.0,
    drawRate: 28.0,
    bookmakerMargin: 5.5,
    historicalVolume: 840,
    accuracyPct: 80.4,
    simulatedRoi: 16.2,
    brierScore: 0.152,
    clvEdge: +4.7,
    bestMarket: 'Ludogorets Win & Over 1.5 / Under 2.5 Midtable',
    worstMarket: 'Away Clean Sheet in Razgrad/Sofia',
    bestModel: 'Dominance Factor & Dixon-Coles Bivariate',
    weakestModel: 'Flat Poisson',
    sources: ['BFS efbet Liga', 'SofaScore Bulgaria']
  },
  canpl: {
    id: 'canpl',
    name: 'Canadian Premier League',
    country: 'Canada',
    flag: '🇨🇦',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'CPL Regular Season & Playoffs',
    active: true,
    dataQualityScore: 93,
    rho: -0.120,
    avgGoals: 2.70,
    homeAdv: 1.26,
    bttsRate: 52.0,
    over15Rate: 75.5,
    over25Rate: 49.0,
    drawRate: 26.5,
    bookmakerMargin: 5.6,
    historicalVolume: 590,
    accuracyPct: 79.8,
    simulatedRoi: 15.6,
    brierScore: 0.155,
    clvEdge: +4.5,
    bestMarket: 'Double Chance & Over 1.5 Goals',
    worstMarket: 'Under 1.5 Goals',
    bestModel: 'Travel Distance & Climate Adjustment Matrix',
    weakestModel: 'Static Pitch Model',
    sources: ['CPL Official Center', 'Transfermarkt Canada']
  },
  croatia: {
    id: 'croatia',
    name: 'Croatian First Football League',
    country: 'Croatia',
    flag: '🇭🇷',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'SuperSport HNL',
    active: true,
    dataQualityScore: 96,
    rho: -0.130,
    avgGoals: 2.65,
    homeAdv: 1.24,
    bttsRate: 50.5,
    over15Rate: 76.0,
    over25Rate: 49.5,
    drawRate: 26.0,
    bookmakerMargin: 5.1,
    historicalVolume: 980,
    accuracyPct: 81.0,
    simulatedRoi: 17.0,
    brierScore: 0.150,
    clvEdge: +5.0,
    bestMarket: 'Dinamo/Hajduk Win & Over 1.5 Goals',
    worstMarket: 'Away Underdogs Clean Sheet',
    bestModel: 'Croatian Big Two Supremacy & Dixon-Coles',
    weakestModel: 'Equal Weight Dispersion',
    sources: ['HNS SuperSport HNL', 'SofaScore Croatia']
  },
  cyprus: {
    id: 'cyprus',
    name: 'Cyprus First Division',
    country: 'Cyprus',
    flag: '🇨🇾',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Cyta Championship Round',
    active: true,
    dataQualityScore: 94,
    rho: -0.125,
    avgGoals: 2.72,
    homeAdv: 1.26,
    bttsRate: 53.0,
    over15Rate: 77.0,
    over25Rate: 51.5,
    drawRate: 25.5,
    bookmakerMargin: 5.3,
    historicalVolume: 820,
    accuracyPct: 80.6,
    simulatedRoi: 16.4,
    brierScore: 0.152,
    clvEdge: +4.8,
    bestMarket: 'Over 2.5 Goals / Both Teams To Score',
    worstMarket: 'Under 1.5 Goals',
    bestModel: 'Mediterranean Heat & High-Conversion Model',
    weakestModel: 'Low-Scoring Northern Model',
    sources: ['CFA Official Data', 'SofaScore Cyprus']
  },
  czech: {
    id: 'czech',
    name: 'Czech Republic First League',
    country: 'Czech Republic',
    flag: '🇨🇿',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Chance Liga Regular Season',
    active: true,
    dataQualityScore: 97,
    rho: -0.115,
    avgGoals: 2.82,
    homeAdv: 1.22,
    bttsRate: 54.5,
    over15Rate: 79.0,
    over25Rate: 53.5,
    drawRate: 24.5,
    bookmakerMargin: 5.0,
    historicalVolume: 1080,
    accuracyPct: 81.5,
    simulatedRoi: 17.2,
    brierScore: 0.149,
    clvEdge: +5.2,
    bestMarket: 'Prague Derby / Slavia-Sparta Dominance (1X)',
    worstMarket: 'Away Clean Sheet at Eden/Letna',
    bestModel: 'Central European Power Index & Dixon-Coles',
    weakestModel: 'Uniform League Dispersion',
    sources: ['Chance Liga Official', 'SofaScore Czech']
  },
  estonia: {
    id: 'estonia',
    name: 'Estonian Premium Liiga',
    country: 'Estonia',
    flag: '🇪🇪',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'Premium Liiga Regular Season',
    active: true,
    dataQualityScore: 91,
    rho: -0.105,
    avgGoals: 2.92,
    homeAdv: 1.23,
    bttsRate: 55.0,
    over15Rate: 80.5,
    over25Rate: 54.0,
    drawRate: 23.5,
    bookmakerMargin: 6.1,
    historicalVolume: 560,
    accuracyPct: 79.2,
    simulatedRoi: 14.9,
    brierScore: 0.157,
    clvEdge: +4.1,
    bestMarket: 'Over 2.5 Goals / Levadia-Flora Dominance',
    worstMarket: 'Under 1.5 Goals',
    bestModel: 'Baltic Scoring Environment Poisson',
    weakestModel: 'Low-Line Under Model',
    sources: ['EJL Premium Liiga', 'Transfermarkt Estonia']
  },
  faroe: {
    id: 'faroe',
    name: 'Faroe Islands Premier League',
    country: 'Faroe Islands',
    flag: '🇫🇴',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'Betri deildin',
    active: true,
    dataQualityScore: 90,
    rho: -0.095,
    avgGoals: 3.10,
    homeAdv: 1.24,
    bttsRate: 59.0,
    over15Rate: 83.5,
    over25Rate: 58.5,
    drawRate: 22.0,
    bookmakerMargin: 6.4,
    historicalVolume: 490,
    accuracyPct: 78.8,
    simulatedRoi: 14.5,
    brierScore: 0.159,
    clvEdge: +3.9,
    bestMarket: 'Over 2.5 & KÍ Klaksvík Dominance',
    worstMarket: 'Under 2.5 Goals',
    bestModel: 'Weather & Wind-Adjusted High-Scoring Engine',
    weakestModel: 'Stiff Defensive Model',
    sources: ['FSF Betri deildin', 'Transfermarkt Faroe']
  },
  finland: {
    id: 'finland',
    name: 'Finnish Veikkausliiga',
    country: 'Finland',
    flag: '🇫🇮',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'Veikkausliiga Mestaruussarja',
    active: true,
    dataQualityScore: 95,
    rho: -0.120,
    avgGoals: 2.74,
    homeAdv: 1.21,
    bttsRate: 52.5,
    over15Rate: 76.5,
    over25Rate: 50.5,
    drawRate: 25.5,
    bookmakerMargin: 5.2,
    historicalVolume: 890,
    accuracyPct: 80.3,
    simulatedRoi: 16.1,
    brierScore: 0.153,
    clvEdge: +4.7,
    bestMarket: 'HJK / KuPS Double Chance & Over 1.5',
    worstMarket: 'Under 1.5 in Summer Rounds',
    bestModel: 'Nordic Artificial Turf & Dixon-Coles Matrix',
    weakestModel: 'Flat Grass Model',
    sources: ['Veikkausliiga Official Feed', 'SofaScore Finland']
  },
  georgia: {
    id: 'georgia',
    name: 'Georgian Erovnuli Liga',
    country: 'Georgia',
    flag: '🇬🇪',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'Crystalbet Erovnuli Liga',
    active: true,
    dataQualityScore: 91,
    rho: -0.140,
    avgGoals: 2.52,
    homeAdv: 1.28,
    bttsRate: 48.0,
    over15Rate: 73.0,
    over25Rate: 46.0,
    drawRate: 28.0,
    bookmakerMargin: 6.0,
    historicalVolume: 570,
    accuracyPct: 79.4,
    simulatedRoi: 15.0,
    brierScore: 0.156,
    clvEdge: +4.2,
    bestMarket: 'Dinamo Batumi/Tbilisi Home Win (1)',
    worstMarket: 'Away Clean Sheet at Batumi',
    bestModel: 'Caucasus Home Altitude & Dixon-Coles',
    weakestModel: 'Neutral Venue Poisson',
    sources: ['GFF Erovnuli Liga', 'Transfermarkt Georgia']
  },
  honduras: {
    id: 'honduras',
    name: 'Honduras Liga Nacional Apertura',
    country: 'Honduras',
    flag: '🇭🇳',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Torneo Apertura Liga Betcris',
    active: true,
    dataQualityScore: 92,
    rho: -0.155,
    avgGoals: 2.42,
    homeAdv: 1.34,
    bttsRate: 46.5,
    over15Rate: 71.0,
    over25Rate: 43.5,
    drawRate: 29.5,
    bookmakerMargin: 5.8,
    historicalVolume: 680,
    accuracyPct: 79.9,
    simulatedRoi: 15.7,
    brierScore: 0.154,
    clvEdge: +4.5,
    bestMarket: 'Olimpia / Motagua Home Win & Under 3.5',
    worstMarket: 'Away Clean Sheet in Tegucigalpa',
    bestModel: 'Clásico Capitalino Fortress Model',
    weakestModel: 'Flat Poisson',
    sources: ['Liga Nacional de Honduras', 'SofaScore Honduras']
  },
  hungary: {
    id: 'hungary',
    name: 'Hungarian NB I',
    country: 'Hungary',
    flag: '🇭🇺',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'OTP Bank Liga',
    active: true,
    dataQualityScore: 95,
    rho: -0.115,
    avgGoals: 2.85,
    homeAdv: 1.22,
    bttsRate: 55.0,
    over15Rate: 79.5,
    over25Rate: 54.0,
    drawRate: 24.5,
    bookmakerMargin: 5.1,
    historicalVolume: 910,
    accuracyPct: 80.8,
    simulatedRoi: 16.7,
    brierScore: 0.151,
    clvEdge: +4.9,
    bestMarket: 'Ferencváros Win & Over 2.5 Goals',
    worstMarket: 'Away Clean Sheet at Groupama Arena',
    bestModel: 'Fradi Supremacy & Dixon-Coles Bivariate',
    weakestModel: 'Uniform Dispersion',
    sources: ['MLSZ OTP Bank Liga', 'SofaScore Hungary']
  },
  iceland: {
    id: 'iceland',
    name: 'Icelandic First Division',
    country: 'Iceland',
    flag: '🇮🇸',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'Besta deild karla',
    active: true,
    dataQualityScore: 92,
    rho: -0.090,
    avgGoals: 3.15,
    homeAdv: 1.23,
    bttsRate: 60.5,
    over15Rate: 84.0,
    over25Rate: 59.5,
    drawRate: 21.5,
    bookmakerMargin: 5.7,
    historicalVolume: 610,
    accuracyPct: 79.6,
    simulatedRoi: 15.9,
    brierScore: 0.155,
    clvEdge: +4.6,
    bestMarket: 'Over 2.5 / Both Teams To Score',
    worstMarket: 'Under 1.5 Goals',
    bestModel: 'High-Pace Atlantic Coastal Scoring Model',
    weakestModel: 'Low-Event Defensive Model',
    sources: ['KSÍ Besta deild', 'Transfermarkt Iceland']
  },
  iraq: {
    id: 'iraq',
    name: 'Iraq Stars League',
    country: 'Iraq',
    flag: '🇮🇶',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Stars League Championship',
    active: true,
    dataQualityScore: 91,
    rho: -0.170,
    avgGoals: 2.22,
    homeAdv: 1.32,
    bttsRate: 41.0,
    over15Rate: 67.5,
    over25Rate: 38.0,
    drawRate: 32.0,
    bookmakerMargin: 6.2,
    historicalVolume: 530,
    accuracyPct: 79.2,
    simulatedRoi: 15.1,
    brierScore: 0.157,
    clvEdge: +4.2,
    bestMarket: 'Under 2.5 Goals / Al-Shorta-Al-Quwa 1X',
    worstMarket: 'Over 3.5 Goals',
    bestModel: 'Mesopotamian Defensive Grid & Dixon-Coles',
    weakestModel: 'High-Scoring Poisson',
    sources: ['Iraqi Stars League Official', 'Transfermarkt Iraq']
  },
  ireland: {
    id: 'ireland',
    name: 'Irish Premier Division',
    country: 'Republic of Ireland',
    flag: '🇮🇪',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'SSE Airtricity Premier Division',
    active: true,
    dataQualityScore: 95,
    rho: -0.135,
    avgGoals: 2.58,
    homeAdv: 1.22,
    bttsRate: 49.5,
    over15Rate: 74.5,
    over25Rate: 47.0,
    drawRate: 27.5,
    bookmakerMargin: 5.3,
    historicalVolume: 870,
    accuracyPct: 80.5,
    simulatedRoi: 16.3,
    brierScore: 0.152,
    clvEdge: +4.8,
    bestMarket: 'Shamrock Rovers / Shelbourne 1X & Under 3.5',
    worstMarket: 'Away Clean Sheet at Tallaght Stadium',
    bestModel: 'League of Ireland Form Trend & Dixon-Coles',
    weakestModel: 'High-Yield Outlier Model',
    sources: ['FAI SSE Airtricity', 'SofaScore Ireland']
  },
  israel: {
    id: 'israel',
    name: 'Israeli Premier League',
    country: 'Israel',
    flag: '🇮🇱',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Ligat ONE ZERO Championship Round',
    active: true,
    dataQualityScore: 96,
    rho: -0.130,
    avgGoals: 2.62,
    homeAdv: 1.24,
    bttsRate: 50.0,
    over15Rate: 75.5,
    over25Rate: 48.5,
    drawRate: 26.8,
    bookmakerMargin: 5.1,
    historicalVolume: 930,
    accuracyPct: 81.1,
    simulatedRoi: 17.0,
    brierScore: 0.150,
    clvEdge: +5.0,
    bestMarket: 'Maccabi Tel Aviv/Haifa Win & Over 1.5',
    worstMarket: 'Underdogs Away Clean Sheet',
    bestModel: 'Levant Dominance Rating & Dixon-Coles',
    weakestModel: 'Uniform Dispersion',
    sources: ['IPFL Ligat HaAl', 'SofaScore Israel']
  },
  kazakhstan: {
    id: 'kazakhstan',
    name: 'Kazakhstan Premier League',
    country: 'Kazakhstan',
    flag: '🇰🇿',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'OLIMPBET QFL Premyer Ligasy',
    active: true,
    dataQualityScore: 92,
    rho: -0.150,
    avgGoals: 2.40,
    homeAdv: 1.30,
    bttsRate: 45.0,
    over15Rate: 70.5,
    over25Rate: 42.0,
    drawRate: 29.0,
    bookmakerMargin: 5.9,
    historicalVolume: 660,
    accuracyPct: 79.9,
    simulatedRoi: 15.5,
    brierScore: 0.154,
    clvEdge: +4.4,
    bestMarket: 'Kairat / Astana Win & Under 3.5 Goals',
    worstMarket: 'Long-Distance Away Road Win',
    bestModel: 'Steppe Travel Fatigue & Artificial Surface Model',
    weakestModel: 'Neutral Field Model',
    sources: ['QFL Kazakhstan', 'Transfermarkt Kazakhstan']
  },
  kosovo: {
    id: 'kosovo',
    name: 'Kosovo Superliga',
    country: 'Kosovo',
    flag: '🇽🇰',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Albi Mall Superliga',
    active: true,
    dataQualityScore: 90,
    rho: -0.145,
    avgGoals: 2.48,
    homeAdv: 1.29,
    bttsRate: 47.0,
    over15Rate: 72.0,
    over25Rate: 45.0,
    drawRate: 28.0,
    bookmakerMargin: 6.3,
    historicalVolume: 510,
    accuracyPct: 78.9,
    simulatedRoi: 14.7,
    brierScore: 0.158,
    clvEdge: +4.0,
    bestMarket: 'Ballkani / Drita Home Win (1)',
    worstMarket: 'Away Clean Sheet at Suhareka',
    bestModel: 'Kosovar Champions Index & Dixon-Coles',
    weakestModel: 'Flat Poisson',
    sources: ['FFK Superliga', 'Transfermarkt Kosovo']
  },
  lithuania: {
    id: 'lithuania',
    name: 'Lithuanian A Lyga',
    country: 'Lithuania',
    flag: '🇱🇹',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'TOPsport A Lyga',
    active: true,
    dataQualityScore: 92,
    rho: -0.125,
    avgGoals: 2.68,
    homeAdv: 1.22,
    bttsRate: 51.0,
    over15Rate: 75.0,
    over25Rate: 48.5,
    drawRate: 26.5,
    bookmakerMargin: 5.8,
    historicalVolume: 640,
    accuracyPct: 79.8,
    simulatedRoi: 15.6,
    brierScore: 0.154,
    clvEdge: +4.5,
    bestMarket: 'Žalgiris Vilnius / Hegelmann Double Chance',
    worstMarket: 'Under 1.5 Goals in Summer Ties',
    bestModel: 'Baltic Attack Tempo & Dixon-Coles',
    weakestModel: 'Stiff Under Model',
    sources: ['A Lyga Official Feed', 'SofaScore Lithuania']
  },
  malta: {
    id: 'malta',
    name: 'Maltese Premier League',
    country: 'Malta',
    flag: '🇲🇹',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: '360Sports Malta Premier',
    active: true,
    dataQualityScore: 91,
    rho: -0.140,
    avgGoals: 2.55,
    homeAdv: 1.20,
    bttsRate: 48.5,
    over15Rate: 73.5,
    over25Rate: 46.5,
    drawRate: 27.5,
    bookmakerMargin: 6.0,
    historicalVolume: 540,
    accuracyPct: 79.3,
    simulatedRoi: 15.0,
    brierScore: 0.156,
    clvEdge: +4.3,
    bestMarket: 'Hamrun Spartans Win & Over 1.5 Goals',
    worstMarket: 'Away Clean Sheet at Ta Qali',
    bestModel: 'Ta Qali Central Stadium Adjusted Engine',
    weakestModel: 'Extreme Home Advantage Model',
    sources: ['MFA Malta Premier', 'SofaScore Malta']
  },
  montenegro: {
    id: 'montenegro',
    name: 'Montenegro First League',
    country: 'Montenegro',
    flag: '🇲🇪',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Meridianbet 1. CFL',
    active: true,
    dataQualityScore: 90,
    rho: -0.155,
    avgGoals: 2.35,
    homeAdv: 1.30,
    bttsRate: 44.0,
    over15Rate: 69.5,
    over25Rate: 41.0,
    drawRate: 30.0,
    bookmakerMargin: 6.2,
    historicalVolume: 480,
    accuracyPct: 78.9,
    simulatedRoi: 14.6,
    brierScore: 0.158,
    clvEdge: +4.0,
    bestMarket: 'Under 2.5 Goals / Buducnost Win (1)',
    worstMarket: 'Over 3.5 Goals',
    bestModel: 'Adriatic Coastal Low-Event Engine',
    weakestModel: 'High-Volume Scoring Model',
    sources: ['FSCG 1. CFL', 'Transfermarkt Montenegro']
  },
  nireland: {
    id: 'nireland',
    name: 'Northern Ireland Premiership',
    country: 'Northern Ireland',
    flag: '🇬🇧',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Sports Direct Premiership',
    active: true,
    dataQualityScore: 95,
    rho: -0.115,
    avgGoals: 2.85,
    homeAdv: 1.24,
    bttsRate: 55.0,
    over15Rate: 79.5,
    over25Rate: 54.0,
    drawRate: 24.5,
    bookmakerMargin: 5.3,
    historicalVolume: 880,
    accuracyPct: 80.6,
    simulatedRoi: 16.5,
    brierScore: 0.151,
    clvEdge: +4.9,
    bestMarket: 'Linfield / Larne Win & Over 1.5 Goals',
    worstMarket: 'Under 1.5 Goals',
    bestModel: 'Belfast Physicality & Dixon-Coles Matrix',
    weakestModel: 'Low-Scoring Neutral Model',
    sources: ['NIFL Premiership', 'SofaScore Northern Ireland']
  },
  serbia: {
    id: 'serbia',
    name: 'Serbia Superliga',
    country: 'Serbia',
    flag: '🇷🇸',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Mozzart Bet SuperLiga',
    active: true,
    dataQualityScore: 96,
    rho: -0.130,
    avgGoals: 2.68,
    homeAdv: 1.26,
    bttsRate: 50.5,
    over15Rate: 76.5,
    over25Rate: 49.5,
    drawRate: 26.5,
    bookmakerMargin: 5.2,
    historicalVolume: 990,
    accuracyPct: 81.2,
    simulatedRoi: 17.1,
    brierScore: 0.149,
    clvEdge: +5.1,
    bestMarket: 'Red Star Belgrade Win & Over 2.5 Goals',
    worstMarket: 'Away Clean Sheet at Marakana',
    bestModel: 'Eternal Derby Hegemony & Dixon-Coles',
    weakestModel: 'Uniform Dispersion',
    sources: ['FSS SuperLiga', 'SofaScore Serbia']
  },
  slovakia: {
    id: 'slovakia',
    name: 'Slovakia Superliga',
    country: 'Slovakia',
    flag: '🇸🇰',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Niké liga Championship Round',
    active: true,
    dataQualityScore: 94,
    rho: -0.120,
    avgGoals: 2.76,
    homeAdv: 1.23,
    bttsRate: 53.0,
    over15Rate: 77.5,
    over25Rate: 51.0,
    drawRate: 25.5,
    bookmakerMargin: 5.4,
    historicalVolume: 870,
    accuracyPct: 80.4,
    simulatedRoi: 16.3,
    brierScore: 0.152,
    clvEdge: +4.8,
    bestMarket: 'Slovan Bratislava Win & Over 1.5 Goals',
    worstMarket: 'Underdogs Clean Sheet at Tehelné pole',
    bestModel: 'Slovan Power Multiplier & Dixon-Coles',
    weakestModel: 'Flat Poisson',
    sources: ['Niké liga Official', 'SofaScore Slovakia']
  },
  slovenia: {
    id: 'slovenia',
    name: 'Slovenia prvaliga',
    country: 'Slovenia',
    flag: '🇸🇮',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'PrvaLiga Telemach',
    active: true,
    dataQualityScore: 94,
    rho: -0.125,
    avgGoals: 2.70,
    homeAdv: 1.24,
    bttsRate: 52.0,
    over15Rate: 76.0,
    over25Rate: 49.5,
    drawRate: 26.0,
    bookmakerMargin: 5.3,
    historicalVolume: 850,
    accuracyPct: 80.5,
    simulatedRoi: 16.4,
    brierScore: 0.152,
    clvEdge: +4.8,
    bestMarket: 'Maribor / Olimpija Ljubljana Win (1X)',
    worstMarket: 'Away Clean Sheet at Ljudski vrt',
    bestModel: 'Večni Derbi & Slovenian Tactical Grid',
    weakestModel: 'High-Scoring Wildcard Model',
    sources: ['NZS PrvaLiga', 'SofaScore Slovenia']
  },
  cymru: {
    id: 'cymru',
    name: 'Cymru Premier',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'JD Cymru Premier Championship Conference',
    active: true,
    dataQualityScore: 93,
    rho: -0.105,
    avgGoals: 2.98,
    homeAdv: 1.24,
    bttsRate: 57.0,
    over15Rate: 81.5,
    over25Rate: 56.0,
    drawRate: 23.5,
    bookmakerMargin: 5.6,
    historicalVolume: 740,
    accuracyPct: 80.1,
    simulatedRoi: 16.1,
    brierScore: 0.153,
    clvEdge: +4.7,
    bestMarket: 'The New Saints (TNS) Win & Over 2.5 Goals',
    worstMarket: 'Under 1.5 Goals in TNS Games',
    bestModel: 'TNS Full-Time Pro Monopoly & Dixon-Coles',
    weakestModel: 'Equal Parity Poisson',
    sources: ['FAW JD Cymru Premier', 'SofaScore Wales']
  },
  vysshaya_liga: {
    id: 'vysshaya_liga',
    name: 'Vysshaya Liga',
    country: 'Belarus',
    flag: '🇧🇾',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'Vysshaya Liga Regular Season',
    active: true,
    dataQualityScore: 93,
    rho: -0.140,
    avgGoals: 2.52,
    homeAdv: 1.25,
    bttsRate: 48.0,
    over15Rate: 72.0,
    over25Rate: 46.0,
    drawRate: 27.5,
    bookmakerMargin: 5.7,
    historicalVolume: 680,
    accuracyPct: 80.3,
    simulatedRoi: 15.9,
    brierScore: 0.153,
    clvEdge: +4.6,
    bestMarket: 'Dinamo Minsk / Neman Grodno Double Chance & Under 3.5',
    worstMarket: 'Away Clean Sheet vs Top 3',
    bestModel: 'Eastern European Pitch Surface & Dixon-Coles',
    weakestModel: 'Uniform Home Advantage',
    sources: ['ABFF Belarus', 'Transfermarkt Belarus']
  }
};

const LEAGUE_ALIASES = {
  'vysshaya_liga': 'vysshaya_liga',
  'vysshaya': 'vysshaya_liga',
  'belarus': 'vysshaya_liga',
  'blr.1': 'vysshaya_liga',
  'misli_premier_league': 'azerbaijan',
  'misli': 'azerbaijan',
  'aze.1': 'azerbaijan',
  'armenian_premier_league': 'armenia',
  'arm.1': 'armenia',
  'israeli_premier_league': 'israel',
  'ligat_haal': 'israel',
  'isr.1': 'israel',
  'uefa.nations': 'uefa_nations',
  'caf.nations': 'afcon',
  'aut.2': 'austria_erste',
  'cyp.1': 'cyprus',
  'cze.1': 'czech',
  'fin.1': 'finland',
  'hon.1': 'honduras',
  'irl.1': 'ireland',
  'isr.1': 'israel',
  'mlt.1': 'malta',
  'nir.1': 'nireland',
  'slv.1': 'slovenia',
  'wal.1': 'cymru',
  'uefa.champions': 'ucl',
  'uefa.europa': 'uel',
  'uefa.europa.conf': 'uecl',
  'rsa.1': 'psl',
  'eng.1': 'epl',
  'esp.1': 'laliga',
  'ita.1': 'seriea',
  'ger.1': 'bundesliga',
  'fra.1': 'ligue1',
  'ned.1': 'eredivisie',
  'por.1': 'ligaportugal',
  'bel.1': 'jupiler',
  'bra.1': 'brasileirao',
  'usa.1': 'mls',
  'mex.1': 'ligamx',
  'tur.1': 'superlig',
  'sco.1': 'scotprem',
  'eng.2': 'championship',
  'aut.1': 'austria',
  'eng.3': 'eng_l1',
  'eng.4': 'eng_l2',
  'fra.2': 'ligue2',
  'ger.2': 'bundesliga2',
  'gre.1': 'greece',
  'ita.2': 'serieb',
  'nor.1': 'eliteserien',
  'rus.1': 'russia',
  'esp.2': 'laliga2',
  'swe.1': 'allsvenskan',
  'sui.1': 'swiss',
  'caf.champions': 'caf_cl',
  'caf.confed': 'caf_cc',
  'afc.champions': 'afc_cl',
  'aus.1': 'aleague',
  'chn.1': 'csl',
  'jpn.1': 'j1',
  'ksa.1': 'saudi',
  'arg.1': 'argliga',
  'bol.1': 'bolivia',
  'chi.1': 'chile',
  'col.1': 'colombia',
  'conmebol.libertadores': 'libertadores',
  'conmebol.sudamericana': 'sudamericana',
  'uru.1': 'uruguay',
  'ecu.1': 'ecuador',
  'par.1': 'paraguay',
  'per.1': 'peru',
  'ven.1': 'venezuela',
  'gua.1': 'guatemala'
};

export function getLeagueById(leagueId) {
  if (!leagueId) return LEAGUE_REGISTRY.epl;
  const key = String(leagueId).toLowerCase().trim();
  const canonical = LEAGUE_ALIASES[key] || key;
  return LEAGUE_REGISTRY[canonical] || LEAGUE_REGISTRY.epl;
}

export function getAllLeagues() {
  return Object.values(LEAGUE_REGISTRY);
}

