/* ============================================================
   NDLELA MILLIONAIRES - CENTRAL LEAGUE REGISTRY & CALIBRATION MATRIX
   Scalable configuration-driven league management system.
   Supports: Multiple seasons, competition phases (Apertura/Clausura),
             travel penalties, venue altitudes, dynamic rho, and historical calibration.
   ============================================================ */

export const LEAGUE_REGISTRY = {
  psl: {
    id: 'psl',
    name: 'Betway Premiership',
    country: 'South Africa',
    flag: '🇿🇦',
    competitionType: 'domestic_league',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 98,
    rho: -0.185,
    avgGoals: 2.15,
    homeAdv: 1.28,
    bttsRate: 42.5,
    over15Rate: 68.2,
    over25Rate: 38.4,
    drawRate: 33.1,
    bookmakerMargin: 5.8,
    historicalVolume: 1840,
    accuracyPct: 80.4,
    simulatedRoi: 18.2,
    brierScore: 0.152,
    clvEdge: +4.8,
    bestMarket: 'Under 2.5 / Match Winner (1X)',
    worstMarket: 'Over 3.5 Goals',
    bestModel: 'Dixon-Coles & Venue Fortress Index',
    weakestModel: 'High-Scoring xG Multiplier',
    sources: ['SofaScore PSL Feed', 'Understat Africa', 'Transfermarkt SA', 'Soccer-Wiki Altitude']
  },
  mls: {
    id: 'mls',
    name: 'Major League Soccer (MLS)',
    country: 'United States & Canada',
    flag: '🇺🇸',
    competitionType: 'domestic_conference',
    season: '2026',
    currentPhase: 'Regular Season & Leagues Cup Phase',
    active: true,
    dataQualityScore: 96,
    rho: -0.100,
    avgGoals: 2.94,
    homeAdv: 1.29,
    bttsRate: 58.6,
    over15Rate: 81.4,
    over25Rate: 56.2,
    drawRate: 23.8,
    bookmakerMargin: 5.2,
    historicalVolume: 1250,
    accuracyPct: 78.8,
    simulatedRoi: 15.6,
    brierScore: 0.161,
    clvEdge: +4.2,
    specialRules: {
      crossCountryTravelPenalty: true,
      conferenceRestDelta: true,
      designatedPlayerWeight: 1.35,
      artificialTurfPenalty: 0.08
    },
    bestMarket: 'Over 2.5 / Both Teams To Score',
    worstMarket: 'Under 1.5 Goals',
    bestModel: 'xG Poisson & Travel Fatigue Model',
    weakestModel: 'Low-Scoring Dixon-Coles',
    sources: ['American Soccer Analysis', 'Opta MLS Feed', 'Transfermarkt MLS', 'Soccer-Wiki Travel Mesh']
  },
  scotprem: {
    id: 'scotprem',
    name: 'Scottish Premiership',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    competitionType: 'domestic_league',
    season: '2026/27',
    currentPhase: 'Regular Phase (Split Post-Matchday 33)',
    active: true,
    dataQualityScore: 95,
    rho: -0.130,
    avgGoals: 2.72,
    homeAdv: 1.22,
    bttsRate: 51.4,
    over15Rate: 76.5,
    over25Rate: 52.0,
    drawRate: 24.5,
    bookmakerMargin: 5.4,
    historicalVolume: 960,
    accuracyPct: 79.2,
    simulatedRoi: 14.8,
    brierScore: 0.158,
    clvEdge: +4.1,
    bestMarket: 'Celtic/Rangers Team Over 1.5 & Match Winner',
    worstMarket: 'Draw No Bet Away Underdogs',
    bestModel: 'Elo Dominance Model',
    weakestModel: 'Flat Poisson',
    sources: ['SPFL Official Data', 'WhoScored SPFL', 'Understat UK', 'Transfermarkt Scotland']
  },
  superlig: {
    id: 'superlig',
    name: 'Trendyol Süper Lig',
    country: 'Türkiye',
    flag: '🇹🇷',
    competitionType: 'domestic_league',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 94,
    rho: -0.120,
    avgGoals: 2.76,
    homeAdv: 1.25,
    bttsRate: 54.2,
    over15Rate: 78.1,
    over25Rate: 53.8,
    drawRate: 25.1,
    bookmakerMargin: 5.6,
    historicalVolume: 1100,
    accuracyPct: 77.9,
    simulatedRoi: 13.9,
    brierScore: 0.165,
    clvEdge: +3.9,
    bestMarket: 'Home Team Goals & Over 2.5',
    worstMarket: 'Clean Sheet Away',
    bestModel: 'Home Fortress & Referee Volatility Model',
    weakestModel: 'Neutral Pitch Model',
    sources: ['TFF Ingestion Feed', 'Mackolik Telemetry', 'WhoScored Turkey', 'Transfermarkt Süper Lig']
  },
  ligamx: {
    id: 'ligamx',
    name: 'Liga MX (Apertura / Clausura)',
    country: 'Mexico',
    flag: '🇲🇽',
    competitionType: 'split_tournament',
    season: '2026/27',
    currentPhase: 'Apertura Tournament (Liguilla Race)',
    active: true,
    dataQualityScore: 95,
    rho: -0.130,
    avgGoals: 2.68,
    homeAdv: 1.26,
    bttsRate: 53.5,
    over15Rate: 77.0,
    over25Rate: 51.4,
    drawRate: 26.2,
    bookmakerMargin: 5.5,
    historicalVolume: 1320,
    accuracyPct: 78.6,
    simulatedRoi: 15.1,
    brierScore: 0.160,
    clvEdge: +4.4,
    specialRules: {
      altitudeFortressFactor: true, // Estadio Azteca (2,240m), Nemesio Diez (2,660m)
      phaseAwareness: ['Apertura', 'Clausura', 'Play-In', 'Liguilla']
    },
    bestMarket: 'Home Win & Altitude Decay (Over 1.5)',
    worstMarket: 'Away Clean Sheet at Altitude',
    bestModel: 'Physics Altitude Decay & Dixon-Coles',
    weakestModel: 'Flat Sea-Level Poisson',
    sources: ['Liga BBVA MX Feed', 'MedioTiempo', 'WhoScored Mexico', 'Soccer-Wiki Altitude']
  },
  eliteserien: {
    id: 'eliteserien',
    name: 'Eliteserien',
    country: 'Norway',
    flag: '🇳🇴',
    competitionType: 'summer_calendar_league',
    season: '2026',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 93,
    rho: -0.095,
    avgGoals: 3.08,
    homeAdv: 1.20,
    bttsRate: 60.1,
    over15Rate: 83.2,
    over25Rate: 59.5,
    drawRate: 22.4,
    bookmakerMargin: 5.7,
    historicalVolume: 740,
    accuracyPct: 77.4,
    simulatedRoi: 14.2,
    brierScore: 0.166,
    clvEdge: +3.8,
    bestMarket: 'Over 2.5 Goals / Both Teams To Score',
    worstMarket: 'Under 1.5 Goals',
    bestModel: 'xG Attack Volume Model',
    weakestModel: 'Defensive Shrinkage Model',
    sources: ['NIFS Norway Feed', 'WhoScored Norway', 'Transfermarkt Norway']
  },
  allsvenskan: {
    id: 'allsvenskan',
    name: 'Allsvenskan',
    country: 'Sweden',
    flag: '🇸🇪',
    competitionType: 'summer_calendar_league',
    season: '2026',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 93,
    rho: -0.110,
    avgGoals: 2.82,
    homeAdv: 1.21,
    bttsRate: 55.4,
    over15Rate: 79.2,
    over25Rate: 54.0,
    drawRate: 25.0,
    bookmakerMargin: 5.6,
    historicalVolume: 720,
    accuracyPct: 78.1,
    simulatedRoi: 14.5,
    brierScore: 0.162,
    clvEdge: +4.0,
    bestMarket: 'Over 1.5 / Match Winner Home',
    worstMarket: 'Correct Score 0-0',
    bestModel: 'Momentum & Artificial Turf Specialist Model',
    weakestModel: 'Low-Scoring Dixon-Coles',
    sources: ['Svenskfotboll Official', 'WhoScored Sweden', 'Transfermarkt Sweden']
  },
  superliga: {
    id: 'superliga',
    name: 'Danish Superliga',
    country: 'Denmark',
    flag: '🇩🇰',
    competitionType: 'split_league',
    season: '2026/27',
    currentPhase: 'Regular Season (Pre-Championship Split)',
    active: true,
    dataQualityScore: 94,
    rho: -0.115,
    avgGoals: 2.86,
    homeAdv: 1.19,
    bttsRate: 56.8,
    over15Rate: 80.5,
    over25Rate: 55.2,
    drawRate: 24.8,
    bookmakerMargin: 5.3,
    historicalVolume: 820,
    accuracyPct: 78.5,
    simulatedRoi: 15.0,
    brierScore: 0.159,
    clvEdge: +4.3,
    bestMarket: 'Both Teams To Score / Over 2.5',
    worstMarket: 'Draw Under 1.5',
    bestModel: 'xG & Field Tilt Ensemble',
    weakestModel: 'Flat Poisson',
    sources: ['Superliga.dk Feed', 'WhoScored Denmark', 'Transfermarkt Denmark']
  },
  championship: {
    id: 'championship',
    name: 'English Championship',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    competitionType: 'domestic_tier2',
    season: '2026/27',
    currentPhase: 'Regular Season (46 Matchdays)',
    active: true,
    dataQualityScore: 97,
    rho: -0.135,
    avgGoals: 2.58,
    homeAdv: 1.23,
    bttsRate: 50.8,
    over15Rate: 74.6,
    over25Rate: 48.9,
    drawRate: 27.2,
    bookmakerMargin: 4.8,
    historicalVolume: 2150,
    accuracyPct: 79.4,
    simulatedRoi: 16.2,
    brierScore: 0.155,
    clvEdge: +4.7,
    bestMarket: 'Double Chance (1X) & Under 3.5 Goals',
    worstMarket: 'Away Clean Sheet',
    bestModel: 'Fatigue Congestion & Dixon-Coles',
    weakestModel: 'High xG Bias',
    sources: ['Opta Championship Feed', 'Understat UK', 'WhoScored UK', 'Transfermarkt UK']
  },
  jupiler: {
    id: 'jupiler',
    name: 'Belgium Pro League (Jupiler)',
    country: 'Belgium',
    flag: '🇧🇪',
    competitionType: 'split_playoffs',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 95,
    rho: -0.110,
    avgGoals: 2.88,
    homeAdv: 1.18,
    bttsRate: 57.2,
    over15Rate: 81.0,
    over25Rate: 56.4,
    drawRate: 24.1,
    bookmakerMargin: 5.2,
    historicalVolume: 990,
    accuracyPct: 78.9,
    simulatedRoi: 15.3,
    brierScore: 0.157,
    clvEdge: +4.4,
    bestMarket: 'Over 2.5 & Team Goals Over 1.5',
    worstMarket: 'Under 1.5 Goals',
    bestModel: 'xG / xT Multi-Model Ensemble',
    weakestModel: 'Low Block Defensive Model',
    sources: ['ProLeague.be Feed', 'WhoScored Belgium', 'Transfermarkt Belgium']
  },
  epl: {
    id: 'epl',
    name: 'Premier League',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 99,
    rho: -0.125,
    avgGoals: 2.82,
    homeAdv: 1.18,
    bttsRate: 54.8,
    over15Rate: 79.5,
    over25Rate: 55.0,
    drawRate: 23.5,
    bookmakerMargin: 3.8,
    historicalVolume: 3400,
    accuracyPct: 81.5,
    simulatedRoi: 16.8,
    brierScore: 0.150,
    clvEdge: +5.1,
    bestMarket: 'Match Winner & Team Over 1.5',
    worstMarket: 'Draw No Bet High Odds',
    bestModel: 'Opta/Understat xG + Dixon-Coles Hybrid',
    weakestModel: 'Unadjusted Elo',
    sources: ['Understat Official', 'Opta EPL Feed', 'WhoScored Premier League', 'Transfermarkt UK']
  },
  laliga: {
    id: 'laliga',
    name: 'LaLiga',
    country: 'Spain',
    flag: '🇪🇸',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 98,
    rho: -0.140,
    avgGoals: 2.54,
    homeAdv: 1.22,
    bttsRate: 49.2,
    over15Rate: 73.8,
    over25Rate: 48.0,
    drawRate: 26.8,
    bookmakerMargin: 4.2,
    historicalVolume: 2900,
    accuracyPct: 80.1,
    simulatedRoi: 15.2,
    brierScore: 0.156,
    clvEdge: +4.6,
    bestMarket: 'Under 3.5 & Match Winner Real/Barca',
    worstMarket: 'High Over Lines (Over 4.5)',
    bestModel: 'Tactical Formations & Dixon-Coles',
    weakestModel: 'Unweighted Poisson',
    sources: ['LaLiga Official', 'Understat Spain', 'WhoScored Spain', 'Transfermarkt Spain']
  },
  seriea: {
    id: 'seriea',
    name: 'Serie A',
    country: 'Italy',
    flag: '🇮🇹',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 98,
    rho: -0.155,
    avgGoals: 2.62,
    homeAdv: 1.19,
    bttsRate: 51.5,
    over15Rate: 75.8,
    over25Rate: 50.4,
    drawRate: 25.9,
    bookmakerMargin: 4.4,
    historicalVolume: 2750,
    accuracyPct: 79.7,
    simulatedRoi: 14.9,
    brierScore: 0.158,
    clvEdge: +4.5,
    bestMarket: '1X Double Chance & Corners Under',
    worstMarket: 'Both Teams To Score in Derby Matches',
    bestModel: 'Dixon-Coles Low Rho & Defensive Elo',
    weakestModel: 'High Pace Poisson',
    sources: ['Lega Serie A Feed', 'Understat Italy', 'WhoScored Italy', 'Transfermarkt Italy']
  },
  bundesliga: {
    id: 'bundesliga',
    name: 'Bundesliga',
    country: 'Germany',
    flag: '🇩🇪',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 98,
    rho: -0.090,
    avgGoals: 3.16,
    homeAdv: 1.16,
    bttsRate: 61.2,
    over15Rate: 84.8,
    over25Rate: 62.4,
    drawRate: 22.0,
    bookmakerMargin: 4.1,
    historicalVolume: 2600,
    accuracyPct: 79.1,
    simulatedRoi: 14.6,
    brierScore: 0.162,
    clvEdge: +4.3,
    bestMarket: 'Over 2.5 / Both Teams To Score',
    worstMarket: 'Under 1.5 Goals',
    bestModel: 'High-Pressing xG & Field Tilt Model',
    weakestModel: 'Low-Scoring Poisson',
    sources: ['DFL Bundesliga Feed', 'Understat Germany', 'WhoScored Germany', 'Transfermarkt Germany']
  },
  ligue1: {
    id: 'ligue1',
    name: 'Ligue 1',
    country: 'France',
    flag: '🇫🇷',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 97,
    rho: -0.135,
    avgGoals: 2.66,
    homeAdv: 1.20,
    bttsRate: 52.0,
    over15Rate: 76.2,
    over25Rate: 50.8,
    drawRate: 25.2,
    bookmakerMargin: 4.6,
    historicalVolume: 2400,
    accuracyPct: 78.9,
    simulatedRoi: 14.3,
    brierScore: 0.161,
    clvEdge: +4.2,
    bestMarket: 'PSG Team Over & Under 3.5 in Midtable clashes',
    worstMarket: 'Away Underdogs Win',
    bestModel: 'Squad Valuation & Tactical Elo',
    weakestModel: 'Flat Poisson',
    sources: ['LFP Ligue 1 Feed', 'Understat France', 'WhoScored France', 'Transfermarkt France']
  },
  eredivisie: {
    id: 'eredivisie',
    name: 'Eredivisie',
    country: 'Netherlands',
    flag: '🇳🇱',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 96,
    rho: -0.085,
    avgGoals: 3.12,
    homeAdv: 1.21,
    bttsRate: 59.8,
    over15Rate: 83.5,
    over25Rate: 61.0,
    drawRate: 21.8,
    bookmakerMargin: 4.9,
    historicalVolume: 1800,
    accuracyPct: 78.4,
    simulatedRoi: 14.7,
    brierScore: 0.163,
    clvEdge: +4.2,
    bestMarket: 'Over 2.5 / PSV & Feyenoord Goals',
    worstMarket: 'Under 1.5 Goals',
    bestModel: 'xG Poisson & Attack Velocity',
    weakestModel: 'Dixon-Coles Low Scoring',
    sources: ['Eredivisie.nl Feed', 'WhoScored Netherlands', 'Transfermarkt Netherlands']
  },
  ligaportugal: {
    id: 'ligaportugal',
    name: 'Liga Portugal',
    country: 'Portugal',
    flag: '🇵🇹',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 96,
    rho: -0.145,
    avgGoals: 2.60,
    homeAdv: 1.23,
    bttsRate: 50.5,
    over15Rate: 75.0,
    over25Rate: 49.5,
    drawRate: 25.8,
    bookmakerMargin: 5.0,
    historicalVolume: 1650,
    accuracyPct: 79.8,
    simulatedRoi: 15.4,
    brierScore: 0.157,
    clvEdge: +4.5,
    bestMarket: 'Big 3 (Benfica, Sporting, Porto) Win & Over 1.5',
    worstMarket: 'Away Clean Sheet for Bottom 8',
    bestModel: 'Top-3 Dominance Elo & Dixon-Coles',
    weakestModel: 'Symmetric Poisson',
    sources: ['Liga Portugal Feed', 'WhoScored Portugal', 'Transfermarkt Portugal']
  },
  saudi: {
    id: 'saudi',
    name: 'Saudi Pro League',
    country: 'Saudi Arabia',
    flag: '🇸🇦',
    competitionType: 'domestic_tier1',
    season: '2026/27',
    currentPhase: 'Regular Season',
    active: true,
    dataQualityScore: 94,
    rho: -0.105,
    avgGoals: 2.98,
    homeAdv: 1.17,
    bttsRate: 58.0,
    over15Rate: 82.0,
    over25Rate: 58.5,
    drawRate: 22.5,
    bookmakerMargin: 5.5,
    historicalVolume: 850,
    accuracyPct: 78.2,
    simulatedRoi: 14.1,
    brierScore: 0.164,
    clvEdge: +4.0,
    bestMarket: 'Top 4 Team Goals (Al Hilal/Al Nassr) Over 1.5',
    worstMarket: 'Draws in Elite Matches',
    bestModel: 'Squad Value Delta & Attack xG',
    weakestModel: 'Flat Elo',
    sources: ['SPL Official Data', 'Transfermarkt Saudi', 'Soccer-Wiki Middle East']
  },
  brasileirao: {
    id: 'brasileirao',
    name: 'Brasileirão Série A',
    country: 'Brazil',
    flag: '🇧🇷',
    competitionType: 'domestic_tier1',
    season: '2026',
    currentPhase: 'Regular Season (38 Matchdays)',
    active: true,
    dataQualityScore: 95,
    rho: -0.160,
    avgGoals: 2.42,
    homeAdv: 1.30,
    bttsRate: 46.8,
    over15Rate: 71.5,
    over25Rate: 44.2,
    drawRate: 28.5,
    bookmakerMargin: 5.1,
    historicalVolume: 1540,
    accuracyPct: 79.5,
    simulatedRoi: 15.8,
    brierScore: 0.156,
    clvEdge: +4.7,
    bestMarket: 'Home Win (1X) & Under 2.5 Goals',
    worstMarket: 'High Scoring Away Wins',
    bestModel: 'Home Fortress & Physical Congestion Engine',
    weakestModel: 'High Pace Poisson',
    sources: ['CBF Official Data', 'GloboEsporte Feed', 'WhoScored Brazil', 'Transfermarkt Brazil']
  }
};

export function getLeagueById(leagueId) {
  if (!leagueId) return LEAGUE_REGISTRY.epl;
  const key = String(leagueId).toLowerCase().trim();
  return LEAGUE_REGISTRY[key] || LEAGUE_REGISTRY.epl;
}

export function getAllLeagues() {
  return Object.values(LEAGUE_REGISTRY);
}
